### ISSUE TITLE
Polly with DynamicProxy interceptor (AOP retry style) - interceptor causes re-entrancy in the async case

### ISSUE THREAD

**Issue by AlexanderSysoev** [App-vNext/Polly#619] opened 2019-03-19 10:53 UTC
For some part of my system I need to add retry logic for reading from the database. I have a number of repositories with async and sync read methods that I can't change. I found a simple solution - interception of all read methods with [DynamicProxy AsyncInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor) and add retry read policy with Polly when database exception caught. Polly retries reading with some intervals.

Interceptor code:

```
public class RetriableReadAsyncInterceptor : IAsyncInterceptor
{
    public void InterceptSynchronous(IInvocation invocation)
    {
        invocation.ReturnValue = InternalInterceptSync(invocation);
    }

    public void InterceptAsynchronous(IInvocation invocation)
    {
        throw new NotImplementedException();
    }

    public void InterceptAsynchronous<TResult>(IInvocation invocation)
    {
        invocation.ReturnValue = InternalInterceptAsync<TResult>(invocation);
    }

    private IEnumerable<TimeSpan> RetryIntervals =>
        new[]
        {
            TimeSpan.FromSeconds(1),
            TimeSpan.FromSeconds(5),
            TimeSpan.FromSeconds(10),
            TimeSpan.FromSeconds(15)
        };

    private object InternalInterceptSync(IInvocation invocation)
    {
        return Policy
            .Handle<DatabaseException>()
            .WaitAndRetry(RetryIntervals, (exception, timeSpan) =>
            {
                Console.WriteLine($"Exception {timeSpan}");
            })
            .Execute(() =>
            {
                invocation.Proceed();
                return invocation.ReturnValue;
            });
    }

    private async Task<TResult> InternalInterceptAsync<TResult>(IInvocation invocation)
    {
        return await Policy
            .Handle<DatabaseException>()
            .WaitAndRetryAsync(RetryIntervals, (exception, timeSpan) =>
            {
                Console.WriteLine($"Exception {timeSpan}");
            })
            .ExecuteAsync(async () =>
            {
                invocation.Proceed();
                var task = (Task<TResult>)invocation.ReturnValue;
                return await task;
            });
    }
}
```

Repository code:
```
public class Repository : IRepository
{
    private int _exceptionsCoutner;

    public Entity GetById(int id)
    {
        if (_exceptionsCoutner <= 2)
        {
            _exceptionsCoutner++;
            throw new DatabaseException();
        }

        //read from db
        return new Entity {Id = id};
    }

    public async Task<Entity> GetByIdAsync(int id)
    {
        if (_exceptionsCoutner <= 2)
        {
            _exceptionsCoutner++;
            throw new DatabaseException();
        }

        //read from db
        return await Task.FromResult(new Entity { Id = id });
    }
}
```
Sync version of GetById works as expected (retries with intervals):
```
Exception 00:00:01
Exception 00:00:05
Exception 00:00:10
```
Async version of GetById retries but not waits for time interval elapsed:
```
Exception 00:00:01
Exception 00:00:01
Exception 00:00:01
```
I can't understand where is the problem. If you have any thoughts - please share.
Full example can be found [here](https://github.com/AlexanderSysoev/RetriableExample).

**Comment by reisenberger** [comment] 2019-03-19 19:05
@AlexanderSysoev Thank you for the clear problem description and full working example. If you step-debug through running your test `Should_retry_when_db_exception_is_thrown_async()` and set appropriate breakpoints, you should see that the code is causing _re-entrancy_ of the `InternalInterceptAsync(...)` method.  

If we change the relevant code to this:

        private object InternalInterceptSync(IInvocation invocation)
        {
            Console.WriteLine("Starting fresh execution through the sync policy.");

            return Policy
                .Handle<DatabaseException>()
                .WaitAndRetry(RetryIntervals, (exception, timeSpan) =>
                {
                    Console.WriteLine($"Exception {timeSpan}");
                })
                .Execute(() =>
                {
                    invocation.Proceed();
                    return invocation.ReturnValue;
                });
        }

        private async Task<TResult> InternalInterceptAsync<TResult>(IInvocation invocation)
        { 
            // Add a breakpoint here when step-debugging.

            Console.WriteLine("Starting fresh execution through the async policy.");

            return await Policy
                .Handle<DatabaseException>()
                .WaitAndRetryAsync(RetryIntervals, (exception, timeSpan) =>
                {
                    Console.WriteLine($"Exception {timeSpan}");
                })
                .ExecuteAsync(async () =>
                {
                    invocation.Proceed();
                    var task = (Task<TResult>)invocation.ReturnValue;
                    return await task;
                });
        }

then the test output confirms the re-entrancy is occurring for the async case:

    Should_retry_when_db_exception_is_thrown_sync
    ===============================
    Starting fresh execution through the sync policy.
    Exception 00:00:01
    Exception 00:00:05
    Exception 00:00:10

    Should_retry_when_db_exception_is_thrown_async
    ===============================
    Starting fresh execution through the async policy.
    Exception 00:00:01
    Starting fresh execution through the async policy.
    Exception 00:00:01
    Starting fresh execution through the async policy.
    Exception 00:00:01
    
I am afraid that I don't know the [DynamicProxy AsyncInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor) library, to know why that re-entrancy might be occurring - or if it is intended that async operations can be invoked multiple times with that library in that way.  You can ask that question of the DynamicProxy AsyncInterceptor library.

We have [unit tests](https://github.com/App-vNext/Polly/blob/ffe99a34edd96d5c5c94075fe22aae8e1a7ed3ed/src/Polly.Specs/Retry/WaitAndRetryAsyncSpecs.cs#L226-L351) confirming that Polly does cycle through the `RetryIntervals` correctly in the async case. 

I see also from your [similar question/answer on StackOverflow](https://stackoverflow.com/a/55242756/) that you experienced similar issues with hand-crafted retry.

**Comment by AlexanderSysoev** [comment] 2019-03-20 07:28
@reisenberger thank for your attention to my problem. It really seems that problem in DynamicProxy libraby. Here is the [comment](https://github.com/castleproject/Core/issues/145#issuecomment-366180469) I found that may be causing such behavior.

**Comment by reisenberger** [comment] 2019-03-20 18:32
Thanks @AlexanderSysoev . I'll close this out soon, on the basis that the issue is not with Polly.

Briefly: Do the repositories you are dealing with have interfaces? If so, you can provide a new class implementing those interfaces, taking in the underlying repository, and the policy to apply:

    public interface IRepository<TEntity>
    {
        async Task<TEntity> GetByIdAsync(int id);
    }

    public ResililentRepository<TEntity> : IRepository<TEntity>
    {
        private readonly IAsyncPolicy policy;
        private readonly IRepository<TEntity> wrappedRepo;

        // Omitted: obvious constructor which takes the above two things as parameters and populates those ^ fields

        public Task<TEntity> GetByIdAsync(int id) => policy.ExecuteAsync(() => wrappedRepo.ExecuteAsync(id));
    }

(Apologies if this is an obvious suggestion which you have already considered and found not possible for your case. Mentioning just in case useful.)

**Comment by AlexanderSysoev** [comment] 2019-03-20 19:15
@reisenberger yeap, that is how I implemented it))

**Comment by reisenberger** [comment] 2019-03-20 20:47
Thanks @AlexanderSysoev . closing this out, as it seems we are concluded.  If we can help with anything else, let us know or open a new issue,

**Closed by reisenberger** 2019-03-20 20:47 UTC
Labels: issue is outside Polly
