### ISSUE TITLE
In async PolicyWrap executions, Context.PolicyKey and Context.PolicyWrapKey may reset to outer values in the PolicyWrap too early

### ISSUE THREAD

**Issue by hamish-rose** [App-vNext/Polly#510] opened 2018-10-03 21:30 UTC
**Summary**: 

Policykey Context property is null when its passed to onRetry delegate when using WaitAndRetryAsync + ExecuteAsync.

Perhaps i'm missing something here, although i'm not able to reproduce if I switch to a synchronous policy.
<br/>

**Expected behavior**: 
after setting PoliyKey when creating policy, its then set on the Context object passed to onRetry delegate.

```
PS C:\Users\hamish.rose\Desktop\test> dotnet run
In on retry. PolicyKey: test, OperationKey: ExecutingMethod
```
<br/>

**Actual behaviour**:
PolicyKey is null on Context object passed to onRetry delegate, even though its set on the policy. 

```
PS C:\Users\hamish.rose\Desktop\test> dotnet run
In on retry. PolicyKey: , OperationKey: ExecutingMethod
```
**Steps / Code to reproduce the problem**: 

```
using System;
using System.Threading.Tasks;
using Polly;
using Polly.Retry;

namespace test
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var policy = Policy.Handle<Exception>()
                  .WaitAndRetryAsync(
                  1,
                  (x, y) => TimeSpan.FromSeconds(5),
                  (ex, timespan, context) => Console.WriteLine($"In on retry. PolicyKey: {context.PolicyKey}, OperationKey: {context.OperationKey}"))
                  .WithPolicyKey("test") as RetryPolicy;

            await policy.ExecuteAsync(async context => await Task.Run(() => throw new Exception()), new Context("ExecutingMethod"));
        }
    }
}
```

**Comment by reisenberger** [comment] 2018-10-04 12:31
Thanks @hamish-rose for the exemplary report and repro code. I can reproduce this. Interestingly, if one executes instead the below (ignoring compiler warnings):

    await policy.ExecuteAsync(async context => { throw new Exception(); }, new Context("ExecutingMethod"));

the issue does not occur.

If my assumptions about the cause are correct, we should be able to push out a fix next week.

**Comment by hamish-rose** [comment] 2018-10-07 09:42
Hey reisenberger

Nice job, I thought it might have been that also. I had a go at fixing in the same way but my unit test was still failing (only updated one overload, must have been the wrong one)

Not a production issue for me - OK to wait for v6.2.0.

**Comment by reisenberger** [comment] 2018-10-07 14:41
@hamish-rose Thanks for the confirmation!

**Comment by reisenberger** [comment] 2018-11-11 10:40
Fix merged to master. Will be live as soon as v6.1.1 is released to nuget

**Closed by reisenberger** 2018-11-11 10:40 UTC
Labels: bug, ready
