### ISSUE TITLE
Read HealthCount of Circuit Breaker

### ISSUE THREAD

**Issue by kaiohenrique** [App-vNext/Polly#825] opened 2021-01-29 19:50 UTC
Any time in future will HealthCount be public for reading (for monitoring purposes)? 

https://github.com/App-vNext/Polly/blob/master/src/Polly/CircuitBreaker/HealthCount.cs

**Comment by martincostello** [comment] 2021-04-11 16:15
Duplicate of #647.

See here for more information: https://github.com/App-vNext/Polly/issues/647#issuecomment-497938998

**Closed by martincostello** 2021-04-11 16:15 UTC
