### ISSUE TITLE
Polly will not build due to errors

### ISSUE THREAD

**Issue by Christian-Oleson** [App-vNext/Polly#815] opened 2021-01-08 03:43 UTC
**Summary**: 
When cloning or forking the current master branch, 568 errors are found. Polly will not build in its current state.

**Expected behavior**: 
The master branch should be kept in a building state so folks can contribute.

**Actual behaviour**:
Master does not build without errors.

**Steps / Code to reproduce the problem**: 
1. Clone master
2. Open the solution in VS
3. Attempt  to build
4. See the errors

**Comment by martincostello** [comment] 2021-01-08 09:15
Hi @Christian-Oleson - could you share some further details?

Using Visual Studio 2019 I have three warnings which break usage of `build.bat` (see #816), but otherwise the solution builds and the tests all pass so I can't reproduce the 568 errors you're seeing.

The build does appear to have an implicit dependency on certain versions of the .NET runtime being installed for running the spec tests (as well as the .NET SDK being installed), but otherwise I don't see any problems.

**Comment by Christian-Oleson** [comment] 2021-01-11 07:24
@martincostello ,
Fee free to close this then. My main concern is that it doesn't build out of the gate. I was going to make a commit, and things didn't build, so I stopped since it looks like the project isn't in a healthy state.

My main concern was to add support for NET Core 3.1, as the other versions have been EOLed and are not under LTS.

**Comment by martincostello** [comment] 2021-01-23 15:12
Thanks again for raising this Christian - this is now resolved in the [`v722-or-v730`](https://github.com/App-vNext/Polly/tree/v722-or-v730) branch.

**Closed by martincostello** 2021-01-23 15:12 UTC
Labels: CI/build
