### ISSUE TITLE
Configuring policies with HttpClientFactory which read or set properties on the HttpRequestMessage

### ISSUE THREAD

**Issue by bramakrishna16** [App-vNext/Polly#689] opened 2019-09-24 21:24 UTC
Below is the code snippet where I am checking for duplicate header insertion when retry happens. I am getting "System.ArgumentNullException: Value cannot be null." error and a high CPU usage.

```
onRetryAsync: async (response, delay, retryCount, context) =>
                        {
                            if (httpRequestMessage.Headers.Contains(HttpConstants.RequestAttemptCountHeader))  // checks for duplicate key insertion
                            {
                                httpRequestMessage.Headers.Remove(HttpConstants.RequestAttemptCountHeader);
                            }

                            httpRequestMessage.Headers.Add(HttpConstants.RequestAttemptCountHeader, retryCount.ToString());
                            string destinationService = (httpRequestMessage.Headers.Contains(HttpConstants.DestinationService) ? httpRequestMessage.Headers.GetValues(HttpConstants.DestinationService).FirstOrDefault() : MetricConstants.Unknown);
                            //logging
                        }
                     );
```

Below is the exception stack trace:
```
ErrorCode:ArgumentNull_<>c__DisplayClass4_1
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.Enter(Object obj)
   at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(String name, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
   at System.Net.Http.Headers.HttpHeaders.Contains(String name)
   at Resilience.TimeoutAndRetryPolicySelector.<>c__DisplayClass4_1.<<SelectNonRootLevelRetryPolicy>b__2>d.MoveNext()
```

I am using AddPolicyHandler() for this.

**Comment by reisenberger** [comment] 2019-09-24 22:02
@bramakrishna16 . See the comparable reports here: https://github.com/dotnet/corefx/issues/26054 . 

I'm not clear which version of .NET Core / Framework you are using, but it seems that the internal storage for [`HttpHeaders`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs) is not a thread-safe dictionary - presumably because concurrent access is not expected.  

From your problem description, it seems possible that the code is causing race conditions (against itself), causing multiple threads to collide in adding to/removing from a non-thread-safe dictionary - hence the exception you are seeing.

Polly in itself is not CPU intensive; is it possible that your retry construction is generating a lot of retries in a tight loop (including retries which overlap), thus high CPU?  

Could you post more complete code? - all policies configured against the given `HttpClient` configuration on `HttpClientFactory`?  (Best of all, a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating the problem, if you can make one.)

A common cause for an async retry loop "treading on itself" (getting into a state of of multiple tries running concurrently) would be that there is some async call somewhere which is not `await`ed. It would be worth checking that has not crept into the code anywhere.

**Comment by bramakrishna16** [comment] 2019-09-25 18:50
@reisenberger, Thanks for the prompt and detailed reply!

I have pasted my code below. I am retrying immediately if I don't get the response for the first time.

Does trying immediately causes this kind of exception when there are multiple requests at the same time?

```
public static IAsyncPolicy<HttpResponseMessage> SelectNonRootLevelRetryPolicy(IServiceProvider sp, HttpRequestMessage httpRequestMessage)
        {
            IPolicyRegistry<string> registry = sp.GetRequiredService<IPolicyRegistry<string>>();
            IAsyncPolicy<HttpResponseMessage> policy = null;
            registry.TryGet<IAsyncPolicy<HttpResponseMessage>>(NonRootRetryPolicyName, out policy);
            RetryLogger logger = sp.GetRequiredService<RetryLogger>();

            if (policy == null)
            {
                TimeoutAndRetryOption settings = sp.GetRequiredService<TimeoutAndRetryOption>();
                policy = Policy<HttpResponseMessage>
                    .HandleResult((response) =>
                    {
                        if (response != null)
                        {
                            return settings.RetriableErrors.Contains((int)response.StatusCode);
                        }
                        else
                        {
                            //No response means we need to try again.
                            return true;
                        }
                    })
                    .Or<TimeoutRejectedException>()
                    .Or<TimeoutException>()
                    .WaitAndRetryAsync(
                        retryCount: settings.NonRootLevelRetryCount,
                        attempt => TimeSpan.FromMilliseconds(0), //retry immediately
                        onRetryAsync: async (response, delay, retryCount, context) =>
                        {
						 if (httpRequestMessage.Headers.Contains("RequestAttemptCountHeader")) //checks for duplicate key insertion
                            {
                                httpRequestMessage.Headers.Remove("RequestAttemptCountHeader");
                            }

                            httpRequestMessage.Headers.Add("RequestAttemptCountHeader", retryCount.ToString());
                            string destinationService = (httpRequestMessage.Headers.Contains("DestinationService") ? httpRequestMessage.Headers.GetValues("DestinationService").FirstOrDefault() : "Unknown");
                            await LogRetry(sp, response, delay, retryCount, settings.RetriableErrors, settings.NonRootLevelRetryCount, destinationService, logger);
                        }
                     );

                registry[NonRootRetryPolicyName] = policy;
            }

            return policy;
        }
```

**Comment by reisenberger** [comment] 2019-09-25 21:21
Thanks @bramakrishna16 . This is what I think is happening.  When you cache the policy in the `IPolicyRegistry<string>`, if the policy is not already there:

    registry[NonRootRetryPolicyName] = policy;

you are caching a `policy` instance with an `onRetryAsync` closure, which closes over (which captures into the closure) the `httpRequestMessage` variable.  That is, the `policy` instance cached in the registry contains a delegate which _captures the single instance of_ `httpRequestMessage` _passed to this method the very first time the method executes, which it caches_ `policy`.

All later executions through the method will not be using the HttpRequestMessage of the later http requests - they will all be using the one single instance `httpRequestMessage` that was passed to the method the first time it executed, which was captured in the closure with the policy.  If this theory is correct, when you have _any_ concurrency of http requests through this policy at a later time, they will be concurrently manipulating the `httpRequestMessage.Headers` dictionary on the same original `httpRequestMessage` instance - hence the exceptions you are seeing arising from concurrently manipulating a non-thread-safe dictionary.

To verify if this theory is correct, just remove all the logic about storing the policy in the policy registry - and see if the problem goes away.

**Comment by reisenberger** [comment] 2019-09-25 21:31
@bramakrishna16 I have some theories why 100% CPU may be being consumed but not enough information to make a strong guess.  It would probably help if you could post:

+ the code of all policies configured on this HttpClient via `HttpClientFactory`
+ the statement where they are configured on `HttpClientFactory` - ie the code with the `AddPolicyHandler()` calls.  It's important to see the order in which the policies are configured.

And some questions: 

+ What is the `HttpClient.Timeout` property set to?
+ What is the typical value of `settings.NonRootLevelRetryCount`?

Thank you.

**Comment by bramakrishna16** [comment] 2019-09-25 23:13
@reisenberger, that was helpful; I will test it from my end and update this thread. Thank you!

Meanwhile, I have answered your questions -

This is the order we are adding policies:
1. SelectTimoutPolicy

```
public static IAsyncPolicy<HttpResponseMessage> SelectTimoutPolicy(IServiceProvider sp, HttpRequestMessage httpRequestMessage)
        {
            IPolicyRegistry<string> registry = sp.GetRequiredService<IPolicyRegistry<string>>();
            TimeoutPolicy<HttpResponseMessage> policy = null;
            
            registry.TryGet<TimeoutPolicy<HttpResponseMessage>>(PollyPolicyConstants.RequestTimeoutPolicyName, out policy);
            RetryLogger logger = sp.GetRequiredService<RetryLogger>();
            if (policy == null)
            {
                TimeoutAndRetryOption settings = sp.GetRequiredService<TimeoutAndRetryOption>();

                policy = Policy.TimeoutAsync<HttpResponseMessage>(
                    timeout: settings.OperationTimeout,
                    timeoutStrategy: TimeoutStrategy.Optimistic,
                    onTimeoutAsync: async (context, timespan, task) =>
                    {
                        await Task.FromResult(true);
                        DateTime now = DateTime.UtcNow;
                        var timeoutException = new TimeoutException(string.Format(
                            System.Globalization.CultureInfo.InvariantCulture,
                            "Timeout occurred while calling service {0}. Activity ID: {1} StartTimeUTC: {2} EndTimeUTC: {3}, Configured RequestTimeout: {4}ms Task was canceled",
                            httpRequestMessage.RequestUri.ToString(),
                            cxt != null ? cxt.ActivityId : Guid.Empty,
                            now.Subtract(timespan).ToString("HH:mm:ss.fffff", CultureInfo.InvariantCulture),
                            now.ToString("HH:mm:ss.fffff", CultureInfo.InvariantCulture),
                            operationTimeout));
                       //logging
                        throw timeoutException;
                    });

                registry["RequestTimeoutPolicy"] = policy;
            }

            return policy;
        }
```

2. SelectNonRootLevelRetryPolicy

```
public static IAsyncPolicy<HttpResponseMessage> SelectNonRootLevelRetryPolicy(IServiceProvider sp, HttpRequestMessage httpRequestMessage)
        {
            IPolicyRegistry<string> registry = sp.GetRequiredService<IPolicyRegistry<string>>();
            IAsyncPolicy<HttpResponseMessage> policy = null;
            registry.TryGet<IAsyncPolicy<HttpResponseMessage>>(NonRootRetryPolicyName, out policy);
            RetryLogger logger = sp.GetRequiredService<RetryLogger>();

            if (policy == null)
            {
                TimeoutAndRetryOption settings = sp.GetRequiredService<TimeoutAndRetryOption>();
                policy = Policy<HttpResponseMessage>
                    .HandleResult((response) =>
                    {
                        if (response != null)
                        {
                            return settings.RetriableErrors.Contains((int)response.StatusCode);
                        }
                        else
                        {
                            //No response means we need to try again.
                            return true;
                        }
                    })
                    .Or<TimeoutRejectedException>()
                    .Or<TimeoutException>()
                    .WaitAndRetryAsync(
                        retryCount: settings.NonRootLevelRetryCount,
                        attempt => TimeSpan.FromMilliseconds(0), //retry immediately
                        onRetryAsync: async (response, delay, retryCount, context) =>
                        {
		          if (httpRequestMessage.Headers.Contains("RequestAttemptCountHeader")) //checks for duplicate key insertion
                            {
                                httpRequestMessage.Headers.Remove("RequestAttemptCountHeader");
                            }

                            httpRequestMessage.Headers.Add("RequestAttemptCountHeader", retryCount.ToString());
                            string destinationService = (httpRequestMessage.Headers.Contains("DestinationService") ? httpRequestMessage.Headers.GetValues("DestinationService").FirstOrDefault() : "Unknown");
                            await LogRetry(sp, response, delay, retryCount, settings.RetriableErrors, settings.NonRootLevelRetryCount, destinationService, logger);
                        }
                     );

                registry["NonRootRetryPolicyName"] = policy;
            }

            return policy;
        }
```

3. SelectRetryTimeoutPolicy

```
public static IAsyncPolicy<HttpResponseMessage> SelectRetryTimeoutPolicy(IServiceProvider sp, HttpRequestMessage httpRequestMessage)
        {
            IPolicyRegistry<string> registry = sp.GetRequiredService<IPolicyRegistry<string>>();
            IAsyncPolicy<HttpResponseMessage> policy = null;
            registry.TryGet<IAsyncPolicy<HttpResponseMessage>>("OperationTimeoutPolicy", out policy);
            if (policy == null)
            {
                //create a new policy and add it to registry.
                TimeoutAndRetryOption settings = sp.GetRequiredService<TimeoutAndRetryOption>();

                TimeSpan requestTimeout = Debugger.IsAttached
                    ? settings.RequestTimeoutForDebugging
                    : settings.RequestTimeout;

                policy = Policy
                    .TimeoutAsync<HttpResponseMessage>(requestTimeout);

                registry["PollyPolicyConstants.RetryTimeoutPolicyName"] = policy;
            }

            return policy;
        }

```
- What is the HttpClient.Timeout property set to?
**10 sec**

- What is the typical value of settings.NonRootLevelRetryCount?
**1**

**Comment by reisenberger** [comment] 2019-09-26 07:50
Thanks @bramakrishna16 . So the code configuring the policies on HttpClientFactory is something like this: ?

    services.AddHttpClient(/* more configuration */)
        .AddPolicyHandler(SelectTimeoutPolicy)
        .AddPolicyHandler(SelectNonRootLevelRetryPolicy)
        .AddPolicyHandler(SelectRetryTimeoutPolicy);

(Please let me know if that is _not_ the order in which the policy configuration statements appear. Thank you.)

**Comment by bramakrishna16** [comment] 2019-09-26 16:24
yes, that sounds right! Thank you!

**Comment by reisenberger** [comment] 2019-09-27 16:58
Hi @bramakrishna16 . I cannot see any obvious reasons for high CPU from the policies quoted and the policy sequence.   Polly itself is lightweight and unlikely to be the direct cause of high CPU.

Potential problems I was looking for (in case you find them, maybe in code I have not seen): something like a high `retryCount:` combined with calls which failed immediately and were then retried immediately (the combination could generate a tight loop, perhaps exacerbated by high concurrency).  

But the cause of the high CPU could be something entirely different - eg threads spinning in lock contention in `System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(...)` (just a guess).

It's hard to offer further suggestions without being able to sit next to you and analyse concurrent thread usage  - and what those threads are doing - when the issue occurs. Suggest taking that approach.

---

One caution: `HttpClient.Timeout == TimeSpan.FromSeconds(10)` is likely too low.  When using Polly retries via HttpClientFactory, `HttpClient.Timeout` becomes an overall timeout to each entire call through HttpClient, including all tries and waits between retries (not a timeout-per-try).  See our [documentation on timeouts with HttpClientFactory](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-applying-timeouts). 

With `HttpClient.Timeout` at 10 seconds, that could mean that your retries are failing immediately anyway - once the `CancellationToken` associated with `HttpClient.Timeout` has signalled, it is not reset again (cancellation tokens are single-use only) - so the retry may be marked already timed out, and throw immediately.

Since you already have `SelectTimeoutPolicy` as an overall timeout, you could set `HttpClient.Timeout` very high (so as not to interfere). You could also consider using `HttpClient.Timeout` instead of `SelectTimeoutPolicy`, but `HttpClient.Timeout` gives you less clear control. A timeout due to `HttpClient.Timeout` usually manifests as `OperationCanceledException`, which is hard to distinguish from other cancellation.

---

Did removing the policy caching within `SelectNonRootLevelRetryPolicy` help?

**Comment by bramakrishna16** [comment] 2019-10-03 17:14
@reisenberger, I was able to resolve multiple headers issue after removing the policy caching! I tested it and works. Thank you very much!

I have couple of follow-up questions:

We don't want to create a policy every time because of latency issues. We want to create it once and re-use the same policy.

Can we store it globally and re-use the same policy using this extension - ` AddPolicyHandler()` ? 
Or Can we create our own custom handler for this purpose?

Thanks for your time!

**Comment by reisenberger** [comment] 2019-10-05 13:16
Hi @bramakrishna16 .  Yes, we can configure a policy using `AddPolicyHandler()` that will act on the particular `HttpRequestMessage` of each request.

Polly offers an execution-scoped [`Polly.Context`](https://github.com/App-vNext/Polly/wiki/Keys-And-Context-Data) class:

+ An individual instance of this class travels with each execution through Polly.  Where policies are configured on an `HttpClient` using HttpClientFactory, a single instance travels with each call through `HttpClient`.
+ That `Polly.Context` [has dictionary semantics](https://github.com/App-vNext/Polly/wiki/Keys-And-Context-Data#using-context-for-custom-data) - you can store any custom data on it.
+ That `Polly.Context` instance is passed to all delegates you can configure on policies, [including the `onRetryAsync`](https://github.com/App-vNext/Polly/blob/4db50346299f62c2373ceba99d2522a8171c9e27/src/Polly/Retry/AsyncRetryEngine.cs#L76) - so you can use it to pass execution-specific data into the `onRetryAsync`, to avoid those [problematic closures](https://github.com/App-vNext/Polly/issues/689#issuecomment-535226843).

So for your case, the strategy will be to pass the execution-specific `HttpRequestMessage` to the `onRetryAsync` as a dictionary value on `Context`.

See here for documentation of the general approach with HttpClientFactory: [Exchanging information between policy execution and calling code](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-exchanging-information-between-policy-execution-and-calling-code).

---

Taking your case in detail:

The `onRetryAsync` in the new `SelectNonRootLevelRetryPolicy` could change to something like: 

```csharp
    onRetryAsync: async (response, delay, retryCount, context) =>
    {
        if (context.TryGetValue("HttpRequestMessageKey", out var messageObject) && messageObject is HttpRequestMessage requestMessage)
        {
            // Rest of this onRetryAsync exactly as before, but acts on the requestMessage passed in via Polly.Context
            if (requestMessage.Headers.Contains("RequestAttemptCountHeader")) //checks for duplicate key insertion
            {
                requestMessage.Headers.Remove("RequestAttemptCountHeader");
            }

            requestMessage.Headers.Add("RequestAttemptCountHeader", retryCount.ToString());
            string destinationService = (requestMessage.Headers.Contains("DestinationService") ? requestMessage.Headers.GetValues("DestinationService").FirstOrDefault() : "Unknown");
            await LogRetry(sp, response, delay, retryCount, settings.RetriableErrors, settings.NonRootLevelRetryCount, destinationService, logger);
        }
    }
```

Where you execute through the policy, you create the `HttpRequestMessage` and store it on the `Polly.Context` before executing:

```csharp
HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, requestUri); // ... for example - or however you need to create your request
var context = new Polly.Context();
context["HttpRequestMessageKey"] = request; // This stores the HttpRequestMessage that the onRetryAsync will pull out (if invoked) during execution.

request.SetPolicyExecutionContext(context);
var response = await client.SendAsync(request);
```

With this technique, you have to use one of the `HttpClient.SendAsync(...)` overloads which takes an `HttpRequestMessage` parameter (as shown above). But you can wrap the code snippet immediately above in a helper extension method on `HttpClient`, to make it more concise to consume.

**Comment by reisenberger** [comment] 2019-10-05 13:26
I noticed: you will likely want to make similar changes for the [`SelectTimeoutPolicy` method](https://github.com/App-vNext/Polly/issues/689#issuecomment-535259620).  This original code in that method:

```csharp
                        var timeoutException = new TimeoutException(string.Format(
                            System.Globalization.CultureInfo.InvariantCulture,
                            "Timeout occurred while calling service {0}. Activity ID: {1} StartTimeUTC: {2} EndTimeUTC: {3}, Configured RequestTimeout: {4}ms Task was canceled",
                            httpRequestMessage.RequestUri.ToString(),
                            cxt != null ? cxt.ActivityId : Guid.Empty,
                            now.Subtract(timespan).ToString("HH:mm:ss.fffff", CultureInfo.InvariantCulture),
                            now.ToString("HH:mm:ss.fffff", CultureInfo.InvariantCulture),
                            operationTimeout));
```

has the same closure problem [discussed here](https://github.com/App-vNext/Polly/issues/689#issuecomment-535226843) - the policy stored in the registry will have an `onTimeoutAsync` delegate which closes over the `httpRequestMessage` instance in scope at the time the policy is stored in the registry. So the logging would always log the `httpRequestMessage.RequestUri` of that first request.

To make sure the policy will log the `httpRequestMessage.RequestUri` of each specific request, you would need to adapt `SelectTimeoutPolicy` using the technique in the previous comment, ie make `onTimeoutAsync` extract the HttpRequestMessage from `context["HttpRequestMessageKey"]`.

---

@bramakrishna16 Hope that helps, and please let me know if you have any questions!

**Comment by reisenberger** [comment] 2019-10-19 11:37
@bramakrishna16 How did you get on with this? Do you need any further information? Otherwise, I will close this in a few days' time.  Thanks

**Comment by udlose** [comment] 2019-10-22 19:48
Just for posterity, the high cpu usage is likely a result of significant exception throwing happening based on @reisenberger 's thought on the `HttpClient.Timeout` being set to low.  Any app in .NET (Core or Framework) with an Exceptions/sec count of ~10 or higher has a significant and measurable impact on CPU.  This can be easily confirmed by looking in the Windows Performance Counters and looking at the "# of Exceps Thrown / sec" counter under the ".NET CLR Exceptions" counter category.  Just make sure to select your specific process to measure (the default setting is across all running processes).

**Comment by reisenberger** [comment] 2019-10-26 17:00
Thanks @udlose . Or originally, it could equally have been the exceptions associated with https://github.com/dotnet/corefx/issues/26054

Closing due to no recent questions. However, @bramakrishna16, if you do need anything else, just post again, and we can gladly pick up the conversation. Thanks

**Closed by reisenberger** 2019-10-26 17:00 UTC
Labels: how-to, question
