### ISSUE TITLE
Build issue with .net4.6.2 getting error in fake generation

### ISSUE THREAD

**Issue by vikash001** [App-vNext/Polly#655] opened 2019-06-13 14:37 UTC
**Summary**: 
@reisenberger 
<br/>
Getting error while building the project. I am using .net4.6.2 framework mine error is 
CS0430  The extern alias 'snh' was not specified in a /reference option [

**Comment by reisenberger** [comment] 2019-06-13 18:20
@vikash001  Please can you provide more information in order for anyone to help.  What project are you getting an error building?  Can you provide a [verifiable example](https://stackoverflow.com/help/mcve) of any problem, so that others can reproduce the issue?  Have you been able to isolate the issue as being connected to Polly? (for instance, does it only appear when Polly is added to the project?)

Have you tried the recommendations in the [documentation for this error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0430)?

Have you tried stackoverflow solutions which refer directly to the error message you are getting, in connection with Fakes?

+ https://stackoverflow.com/questions/49140203/error-the-extern-alias-snh-was-not-specified-in-a-reference-option-in-a-c
+ https://stackoverflow.com/questions/52267170/error-cs0430-the-extern-alias-snh-was-not-specified-in-a-reference-option-u

Thank you

**Comment by vikash001** [comment] 2019-06-14 13:18
@reisenberger , I am using Polly in 7.1.0.0 in my project that is using net 462. And Now I am using this project integration with mine another project. I start getting an error like 
CS0430 The extern alias 'snh' was not specified in a /reference option 
After it, I start resolving according to a post on GitHub but my problem did not resolve
https://github.com/dotnet/sdk/issues/2254#issuecomment-466219736
 
There are people talking about .netstandared2.0 and .netframework 462 compatible issues in library system.net.http and system.io.compression

**Comment by reisenberger** [comment] 2019-06-16 19:49
Thanks @vikash001 . Yes, it is widely reported that there are several issues with .NET4.6.2 compatibility to .NET Standard 2.0; and those same issues are affecting Fakes, as reported on https://github.com/dotnet/sdk/issues/2254 and discussed at greater length here: https://developercommunity.visualstudio.com/content/problem/162321/fakes-not-generated-using-net-471-after-updating-t.html. 

These issues are outside Polly and I believe not something the Polly team can solve for you.  

---

I can think of the following options (each an alternative), which you could try:

(1) Upgrade your project/s to .NET4.7.2 if possible (consuming the existing Polly nuget).  Upgrading to .NET4.7.2 is the [official recommendation from MS for these cases](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support); see footnote 2 of that link.

(2) (_only if (1) above does not resolve_) Upgrade your project/s to .NET4.7.2. Fork the Polly package, add an explicit .NET4.7.2 target [here](https://github.com/App-vNext/Polly/blob/521728bc19d8390a9dd043d77b13096d3b49326e/src/Polly/Polly.csproj#L4) and run the [build](https://github.com/App-vNext/Polly/blob/521728bc19d8390a9dd043d77b13096d3b49326e/build.bat) to build a Polly nuget package with an explicit .NET4.7.2 target (found in artifacts folder).  See if using that Polly nuget in conjunction with your project/s (upgraded to 4.7.2) resolves the issue.  

_This (2) should not behave any differently from (1), as .NET4.7.2 is considered fully compatible with .NET Standard 2.0. However, if (1) fails, I would be interested to hear if this behaved any different._

(3) Leave your project/s at .NET4.6.2.  Add an explicit .NET4.6.2 build target for Polly as described under (2).  See if consuming a Polly nuget with an explicit .NET4.6.2 target resolves the issue.

_We might be cautious about publishing Polly with an explicit .NET4.6.2 target ([notwithstanding this](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)), due to reports that adding an explicit .NET4.6.1-.NET4.7.1 target can make the experience worse for .NET4.7.2 consumers. Reference: https://github.com/dotnet/docs/issues/8896#issuecomment-449714434_ . 

(4) Wait for the fixes promised on https://github.com/dotnet/sdk/issues/2254 

(5) Try any of the solutions described here: https://developercommunity.visualstudio.com/content/problem/162321/fakes-not-generated-using-net-471-after-updating-t.html

---

Please let me know if this thinking is helpful, and if any option resolves the issue for you.

**Comment by vikash001** [comment] 2019-06-17 13:04
@reisenberger, I tried the solution changing the Polly target frameworks.  at net462 build getting succeed in visual studio but not able to publish to artifacts. Getting network issues because I have multiple sources of nuget.  I did following changes to project.
<TargetFrameworks>netstandard1.1;netstandard2.0;net462</TargetFrameworks>
<ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

**Comment by vikash001** [comment] 2019-06-18 08:39
@reisenberger , Solution 3 works for me. I did build on .net462 and used that dll in my project. But I tried to run your command to publish on artifacts that do not work because It is picking up our orgs default nuget resources.

**Comment by reisenberger** [comment] 2019-06-19 06:26
@vikash001 Did option (1) from [above comment](https://github.com/App-vNext/Polly/issues/655#issuecomment-502480531) work for you? Is it an option for you?

**Comment by vikash001** [comment] 2019-06-19 09:24
@reisenberger , PR [dotnet/sdk#2254](https://github.com/dotnet/sdk/issues/2254) Merged. Could u help incorporate this PR in Polly.

**Comment by reisenberger** [comment] 2019-06-19 18:32
@vikash001 I can't do anything on the Polly side to expedite use of those changes.  The changes in https://github.com/dotnet/sdk/pull/3331 are changes to the build system built into Visual Studio and the `dotnet` cli, as far as I understand.  

The issue is milestone tagged to [v3.0.1xx](https://github.com/dotnet/sdk/milestone/15?closed=1).  It will probably (soon) be part of an SDK `v3.0.100-preview*` release at https://dotnet.microsoft.com/download/dotnet-core/3.0, but you may also be able to try it sooner by using the daily builds at https://github.com/dotnet/core/blob/master/daily-builds.md#future-releases ; there are instructions how here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md . 

_I could be wrong about how you should consume the changes_ depending on where the error occurred for you - ask (say on https://github.com/dotnet/sdk/issues/2254) when the changes are likely to be released generally available, or how to use a daily build to consume them sooner, if you are unsure.

**Comment by reisenberger** [comment] 2019-06-25 06:04
Closing as I think we are done here.  However, please comment if you need any further assistance and we can gladly re-open.

**Closed by reisenberger** 2019-06-25 06:04 UTC
Labels: issue is outside Polly, question
