### ISSUE TITLE
Retry: Original Exception on Cancellation

### ISSUE THREAD

**Issue by Discofunk** [App-vNext/Polly#432] opened 2018-04-06 19:21 UTC
Would it make sense to include the last exception as an inner exception of `OperationCanceledException` when a retry is cancelled with a `CancellationToken`?

In the `RetryEngine` Polly uses: `cancellationToken.ThrowIfCancellationRequested();`

This will throw an `OperationCanceledException` but we loose context in regard to what the exception was from the last retry.  This might be useful to retain.

Instead of using `ThrowIfCancellationRequested();` would it be better to do something similar to:
```
if (cancellationToken.IsCancellationRequested)
{
    throw new OperationCanceledException("????", lastRetryException, cancellationToken);
}
```

**Comment by reisenberger** [comment] 2018-04-06 21:47
Thanks @discofunk for this suggestion.  There are a few reasons why it is not easy to carry through consistently:

+ Polly policies handle both return values and exceptions; the `InnerException` approach could only apply (directly) to communicate exceptions which cause the previous retry, not return values. 
+ If we did this, we’d need to make sure it applied consistently – which means applying it also to cancellations which occur during the wait phase of wait-and-retry or are thrown by executed user delegates. To apply the same principle to those cases, Retry would have to catch the `OperationCanceledException` they throw, and then rethrow with the cause-of-previous-retry-exception as the `InnerException` ... but that means discarding the info/stack trace of the original cancellation ... (which should rightfully be the `InnerException` if we rethrow as a different exception). ... or using an `AggregateException` to preserve both ... the complications just compound.

I also feel uncomfortable about the Polly API breaking the standard idiom of what `InnerException` means in [the documentation](https://msdn.microsoft.com/en-us/library/dd414751(v=vs.110).aspx). that `InnerException` should be ‘the cause of the current exception’ and only be set for ‘an exception that is thrown as a direct result of a previous exception’. 

---

How else could you obtain, on cancellation, the cause of a previous retry (if any)?

The exception-causing-the-retry _is_ passed to the `onRetry` delegate (if configured) of the retry policy.  So you can either: 

+ _if_ policy definition and usage are in the same scope, have `onRetry` store the exception-causing-retry in a local variable, and refer to it afterwards
+ _if_ policy definition and usage are not in the same scope, pass a `Context` into the execution, have `onRetry` store the exception-causing-retry in the `Context`, and extract it from the `Context` after execution.

Does this help?

---

On the other hand, if the context is the scenario from [your other question](https://github.com/App-vNext/Polly/issues/431#issue-310967559), you could certainly choose yourself to use the `InnerException` of the `OperationCanceledException` as you suggest:

```
var policy = Policy
    .Handle<OfflineException>()
    .Retry(3, (ex, retryAttempt, ctx) =>
    {
        var result = MessageBox.Show("Please retry once the application is back online or cancel this request", "Application Offline", MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
        if (result != DialogResult.Retry)
        {
           throw new OperationCanceledException("????", ex, cancellationToken);
        }
    });
```

**Comment by reisenberger** [comment] 2018-04-10 07:26
Closing as I believe we have a resolution for the question raised.  However, do please reopen - or open another issue - if you have further questions.

**Closed by reisenberger** 2018-04-10 07:26 UTC
Labels: wontimplement

**Comment by Discofunk** [comment] 2018-04-11 15:10
Thanks for the suggested alternatives - I will take a look.
