### ISSUE TITLE
[IIS express known issue] When using IISExpress with latest v7 Polly, app pool restarts cause IISExpress to crash

### ISSUE THREAD

**Issue by nicholashead** [App-vNext/Polly#628] opened 2019-04-02 00:19 UTC
**Summary**: 

To preface, this may be something in our specific config/usage of Polly - however I wanted to file in case anyone else is encountering this weirdness. We use IISExpress locally to do development on our site. After updating from Polly v6 to v7 - whenever we re-build the solution and refresh (and IISExpress shuts down the app, and spins it back up), IISExpress will crash. The console does not say anything is wrong, but the Windows Event log has:

Application: iisexpress.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFDB2DCA4BF (00007FFDB2C90000) with exit code 80131506.

--

Faulting application name: iisexpress.exe, version: 10.0.14358.1000, time stamp: 0x574fb9e6
Faulting module name: clr.dll, version: 4.7.3362.0, time stamp: 0x5c2fcfd4
Exception code: 0xc0000005
Fault offset: 0x000000000013a4bf
Faulting process id: 0x8a5c8
Faulting application start time: 0x01d4e8e42d82d2c4
Faulting application path: C:\Program Files\IIS Express\iisexpress.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 6a06573f-4e42-4a3f-88fb-71a370c3de53
Faulting package full name: 
Faulting package-relative application ID: 

--

Downgrading back to v6 solves this problem for me, every time. So something changed from v6 to v7 that IISExpress (or our specific site config/build) doesn't like.

<br/>
<br/>

**Expected behavior**: 

For IISExpress to not crash with Polly v7.

<br/>
<br/>

**Actual behaviour**:

IISExpress crashes hard upon upgrade to Polly v7.

<br/>
<br/>

**Steps / Code to reproduce the problem**: 

Best is a [complete example](https://stackoverflow.com/help/mcve) or failing unit test.  It is _always_ useful to see:

+ **code of any policy declarations**, 
+ **code of calls to `.Execute/AndCapture/Async(...)`**

We only actually use Polly in a handful of places in our codebase, here's some examples:

```cs
_retryPolicy = Policy.Handle<Exception>().WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(i + 1), (exception, timeSpan) =>
               {
                   Logger.Warn("Retrying Query", new { exception = exception.ToString(), timeSpan = timeSpan.ToString() });
               });
```

```cs
var output = Policy
                .Handle<TimeoutException>()
                .Or<RedisServerException>()
                .Or<RedisException>()
                .Or<AggregateException>(
                    ae => ae.InnerExceptions.Any(ie => ie is TimeoutException || ie is RedisServerException ||
                                                       ie is RedisException));
```

**Comment by reisenberger** [comment] 2019-04-02 17:48
@nicholashead This is a known issue with [Referencing a net standard library in classic asp.net projects](https://github.com/dotnet/standard/issues/873) which is not specific to Polly, since it clearly emerged September 2018, before Polly v7 was released.

Nonetheless, it's very interesting that Polly v6 does not experience the issue while Polly v7 does. I'll aim to pass on details to the Microsoft team of exactly what changed between Polly v6 and v7, in case it helps them pinpoint the issue.  Short answer: the main significant differences in the way Polly v7 uses the underlying Base Class Library, compared to Polly v6, are:

+ the [re-introduction of binary serialization](https://github.com/App-vNext/Polly/commit/e37704e0849cb7438fc6b7de743206ac29a0ca2c) (net standard 2.0 tfm only); 
+ the [adoption of `System.ValueTuple`](https://github.com/App-vNext/Polly/commit/39f26a6226d47c9fe104e59191d804a2f0c266c3) (natively in net standard 2.0 tfm; via nuget package for net standard 1.1).

**Comment by reisenberger** [comment] 2019-04-02 17:57
@nicholashead If I could generate you nuget packages omitting each of the two changes listed above, would you be will to trial them to see whether we can pinpoint the issue?

**Comment by nicholashead** [comment] 2019-04-02 18:52
@reisenberger thanks for the reply! That referenced issue is very interesting. I'm not sure why v6 is working for us but v7 is not. And yes I can definitely trial to help figure this out at all.

**Comment by reisenberger** [comment] 2019-04-03 20:27
@nicholashead Awesome! Thanks for offering to trial these packages, to help diagnose what IIS Express may be choking on.

_The files below are uploaded as_ `.zip` _to keep github happy. Rename to_ `.nupkg` _and you can consume them locally as nuget packages_. 

This first package below includes binary serialization but omits use of ValueTask: if the issue with IIS Express is definitively not there using this package, it would suggest ValueTask was a cause/trigger:

[Polly.7.0.0-d7e5825-YesBinarySrlznNoValueTask.zip](https://github.com/App-vNext/Polly/files/3040573/Polly.7.0.0-d7e5825-YesBinarySrlznNoValueTask.zip)

This second package below omits both binary serialization and ValueTask: if the issue with IIS Express reproduced when using the above package, but not when using the below package, it would suggest Binary Serialization was a cause/trigger:

[Polly.6.1.2-2d35b30-noBinarySrlznOrValueTask.zip](https://github.com/App-vNext/Polly/files/3040585/Polly.6.1.2-2d35b30-noBinarySrlznOrValueTask.zip)

---

I am not making any predictions 🙂 . Those two language usages seemed the most significant changes in what Polly v7 consumes of the .Net Standard surface area, that Polly v6 doesn't.  But these very-much-guesses could still be off the mark.

Thanks for your help!

**Comment by nicholashead** [comment] 2019-04-03 20:52
@reisenberger thanks so much for taking the time to make those. i'll give them a whirl and report back.

**Comment by nicholashead** [comment] 2019-04-03 21:10
@reisenberger 
`Polly.7.0.0-d7e5825-YesBinarySrlznNoValueTask.zip built from d7e5825` works correctly - does not cause IISExpress to crash.

**Comment by reisenberger** [comment] 2019-04-05 18:39
@nicholashead Awesome! Thanks so much for checking that out.  If you have time - for ultimate precision, are you happy to test this one?

[Polly.7.0.0-39f26a6-UsesValueTuple.zip](https://github.com/App-vNext/Polly/files/3049180/Polly.7.0.0-39f26a6-UsesValueTuple.zip) from [39f26a6](https://github.com/App-vNext/Polly/commit/39f26a6226d47c9fe104e59191d804a2f0c266c3), exactly one commit later than d7e5825, plus [d4ec6f4](https://github.com/App-vNext/Polly/commit/d4ec6f43fd29d75f058302c58c4e04c8444b9287) layered on manually to correctly state nuspec dependencies.

By adding just one commit (plus the nuspec change), we can hopefully point the Microsoft folks very precisely at the cause (or at least one cause) . 

Thanks again.

**Comment by nicholashead** [comment] 2019-04-08 15:53
@reisenberger that one triggers the problem/error - IISExpress crashes upon recycle.

**Comment by nicholashead** [comment] 2019-04-08 15:54
Also, I wanted to note - I'm now using the IISExpress that comes with Visual Studio 2019 (it upgraded it apparently) - which is version 10.0.17763.1

**Comment by reisenberger** [comment] 2019-04-09 19:10
@nicholashead Awesome! Noted [to the Microsoft teams](https://github.com/dotnet/standard/issues/873#issuecomment-481395947).  Thanks for your collaboration in pin-pointing!

**Comment by reisenberger** [comment] 2019-06-25 06:22
Closing as there is nothing further to do on the Polly side on this issue.  However, I'm tracking https://github.com/dotnet/standard/issues/873 and will comment again here when that resolves.

**Closed by reisenberger** 2019-06-25 06:22 UTC
Labels: issue is outside Polly
