### ISSUE TITLE
Feature Request/Thought: Ability to control via configuration the Policy and Policy Details

### ISSUE THREAD

**Issue by gramanero** [App-vNext/Polly#50] opened 2015-11-03 17:47 UTC
I was wondering if it would be helpful (or a hindrance) if some of the pieces of information such as retry counts and the actual policy being used were configurable thereby preventing the need for a code change but instead a configuration change.

We could have a NuGet package, say Polly.Config, with one dependency (Polly). When installed, it automatically adds a configuration section to the project’s web config as a sort of template to be tweaked:
`<configuration>`
`<configSections>`
`<section name="RetryPolicies"
             type="Polly.Config.RetryPoliciesSection.RetryPoliciesSection, Polly.Config" />`
`</configSections>`
`<RetryPolicies>`
`<Policies>`
`<Policy name="MyRetryPolicy" retryType="WaitAndRetry" retryDelayMs="25,50,75,100" />`
`<Policy name="None" retryType="None" />`
`<Policy name="RetryOnce" retryType="RetryOnce" />`
`<Policy name="RetryNTimes" retryType="RetryNTimes" retryCount="5" />`
`<Policy name="WaitAndRetry" retryType="WaitAndRetry" retryDelaysMs="50,100,150,200,250" />`
`<Policy name="RetryForever" retryType="RetryForever" />`
`<Policy name="CircuitBreaker" retryType="CircuitBreaker" triggerCount="5" timeoutMs="5000" />`
`</Policies>`
`</RetryPolicies>`
`</configuration>`

These are just place-holder elements to showcase the available policies and how they should be configured. I added one at the top (i.e. MyRetryPolicy) that is referenced in the code snippet below.

Consuming a named policy in code looks like this (not using a name will default to a policy named “Default”):
`public class RetryProvider : IRetryProvider`
`{`
`public Task<T> ExecuteAsync<T>(Func<Task<T>> executionFunction)`
`{`
`return ConfiguredPolicy.HandleAsync<Exception>("MyRetryPolicy")`
`.ExecuteAsync(executionFunction);`
`}`
`}`

If we were to have done this using just Polly, it would have looked something like this:
`public Task<T> ExecuteAsync<T>(Func<Task<T>> executionFunction)`
`{`
`return Policy`
`.Handle<Exception>()`
`.WaitAndRetryAsync(new [] { 25, 50, 75, 100}.Select(x => TimeSpan.FromMilliseconds(x)))`
`.ExecuteAsync(executionFunction);`
`}`

You can see that all we’ve done is replace the configuration step. Now we can just inject this RetryProvider and use it anywhere we’re going over a network. For example,
`RedisValue result = await retryProvider.ExecuteAsync(() => redisCache.StringGetAsync(key));`
`if (!result.HasValue)`
`return null;`

Again the idea is that it would mean changing the magic numbers of the policy and even the policy itself becomes a configurable piece should that be desired and therefore can be quickly tweaked before and after something like performance testing or in production if problems arise.

Thoughts as to whether this is a good or bad idea?

**Comment by reisenberger** [comment] 2016-01-24 11:58
@gramanero This seems like a strong idea for the reasons you mention (ability to tweak policies in production without recompiling and redeploying code).  AppvNext are planning to look at a longer-term roadmap, and I will place this on the table for discussion.  If you do develop / are continuing to develop any complete sample in this direction, do let us know - open source projects depend on contributions from the community to implement all the available ideas!

My instinct would be for (as you suggest) a separate NuGet package.  

If you are already developing this in any way: I saw that Ian Cooper's Brighter / paramore project https://github.com/iancooper/Paramore already uses a string-name-identified registry of Polly policies.  Don't know if there might be any mileage in contacting that project to see if they are interested in this feature too? (possible collaboration / or could be developed in a way that would fit them). (NB no idea if they may or may not be interested - no prior contact with them - just a thought).

Thanks.

**Comment by gramanero** [comment] 2016-04-21 19:44
@reisenberger  Wow, so I never saw the email notification telling me that anyone responded to my suggestion. I really appreciate you taking the time to respond (like ... way back in January). We do have a NuGet package in use currently that wraps up the functionality I was asking about. I will take a look at the Paramore project to see what that is all about. 

Thanks for pointing me off in that direction and for capturing this idea on the roadmap!

**Comment by reisenberger** [comment] 2016-04-21 20:02
@gramanero Thanks!  Is the nuget package you use for this something you would be happy to share details about?  (I couldn't find anything obvious...)

**Comment by gramanero** [comment] 2016-04-25 12:09
@reisenberger Yes, absolutely. In fact, the details of the actually package that we are using were included in the first post that I made on this topic. I changed some names around in the post, but the configuration structure and C# logic were pulled directly from the package that was built. To contribute it back to the community I would just need to change around the name spacing of the code and package and make any other changes necessary based on feedback. If this is something that you feel would be of value, then we can work together to get this done. I have never contributed back to the community but think this would be a good, simple start for me and the organization that I work for to start giving back.

I will likely need a little guidance on how to go about creating a fork of the based code, etc. Having not gone thru this process before I certainly don't want to mess anything up.

Thanks!

**Comment by joelhulen** [comment] 2016-04-25 15:37
@gramanero We're absolutely thrilled that you are contributing back to the community by making Polly better! We've written up guidance [on our wiki](https://github.com/App-vNext/Polly/wiki/Git-Workflow) about steps you can take to contribute, including a link within to learn more about forking code. Let us know if you get stuck with any of the steps.

@reisenberger I believe that we could use a new NuGet package that provides async features for the 4.0 framework. If you agree, we could discuss whether this should be part of the current project, or a spin-off.

**Comment by gramanero** [comment] 2016-04-26 12:24
@joelhulen Thanks Joel. Like I said...it'll be a bit of a learning process for me so I am sure I'll have a fair number of questions. Thanks for FWing the links. I am traveling this week so I will likely have a chance to read thru some of the information before attempting to create a fork and begin to integrate the work. Which brings up the questions you are asking @reisenberger .

Right now the package, named OEC.Core.PollyConfig (which I will re-namespace), relies on .NET 4.5.1 and has a single dependency, that being Polly @ version 2.2.3. So this PollyConfig package wraps the base Polly package to add the support for configuration. I am not sure if that is a better approach as opposed to integrating the work directly into the base Polly package. I tend to like the idea of keeping the packages separate (although I can see where that might be a pain to manage keeping the packages inline with one another) in order to reduce the overall size ov the base Polly package in the long run. Just my .02$ and I am new to this, so feel free to provide suggestions, advice, and direction. ;-)

As a side note, I work for OEConnection (that is what the 'OEC' in the namespace stands for) out of Richfield, OH. I am trying to find some small opportunities to get the development staff here to give back to the open source community and I feel like this is a nice, small, starting point. I am going to run with this first one an then I hope to grow the idea from here.

**Comment by reisenberger** [comment] 2016-04-27 18:52
Hey @gramanero, great to hear you are interested in contributing.

@joelhulen My take on the packaging is also to keep the package separate.  Alternate configuration methods (this, or by attribute #87) feel like 'add-ons' with a distinct boundary; some users will love them [we could use this :smile: ], but others will have no interest (not want to config their policies that way), and not need this in the main package.  By keeping them separate, we reduce the complexity of the main package (including of overload options presented to users).  However, open.  Do you have views?

Seems like a first decision worth resolving, as affects whether we / @gramanero establish a new repo, or fork from the existing Polly.  (Although we cld still switch this decision later in the dev process.)

**Comment by reisenberger** [comment] 2016-05-14 20:16
Hey @gramanero . I think a next step (if you happy) would be for you to upload a copy of the code you have to some repository on https://github.com/gramanero . The Polly team can then get sight of the code and we can explore together the best way to structure an adjunct to Polly.

One aspect on my radar is that there may be some beneficial overlap with #87 (apply policies from attributes).  I'm wondering if the configure-policies-from-config approach perhaps has elements of [i] extract, [ii] store and [iii] apply.  #87 probably also needs some kind of [ii] store ('Policy Registry'?), and is a method of [iii] applying.  

We might (speculating here...) eventually end up with something like separate packages `Polly.Config`, `Polly.Registry`, `Polly.Attribute` (of which people pull in the bits they need) ... But speculating - hence, a useful first step would be to see any existing code, then we can begin to reason about the best way to structure this.

Thanks!

**Comment by gramanero** [comment] 2016-05-15 11:38
Hi @reisenberger. This has been on my mind so thanks for the push. Sorry
for the lack of attention to tis recently. My summers get filled with
mountain bike races and training, so I expect to have a bit of time now
until the beginning of June.

I am guessing I should re-namespace the project first and then stick it
into github? Probably makes the most sense. Figure I will just go with how
we have been discussing it here as Polly.Config. I really like the idea of
making it a separate package and treating this more as an add-on capability
for others to consume when/if they feel it will add value and not have it
unnecessarily clutter up the main line Polly package, but I am certainly
open to whatever the group feels would be a more maintainable approach.

I will get to work on this today and this coming week if this all sounds
good.

Thanks!

**Comment by reisenberger** [comment] 2016-05-15 12:49
Hi @gramanero All sounds great (agree w your naming suggestions).  No pressure at all about timing - we all have other things on - and no shortage of other things in dev w Polly at the mo anyway. :smile_cat:

**Comment by pvmraghunandan** [comment] 2016-07-05 09:41
Is it just for configuration driven? I think we should also support end systems which can maintain configuration in different way like JSON as example. But I am more interested on handling predicates. How are we planning to achieve it? And if the policy is generic type, how can we compile dynamically?

**Comment by reisenberger** [comment] 2016-07-05 18:03
@pvmraghunandan Great to have your comments! - parallels a lot of the thinking at App-vNext.
 
Yes: a general `PolicyRegistry` class or similar could take input from any number of pluggable sources: config files; json; whatever...

As your comment suggests, though, configuring anything involving a lambda from flat config files, at runtime, would be hard.  That includes predicates specifying what exceptions / results to handle (beyond more-or-less simple matching); and any of the lambda state-change delegates that policies can also take: `onRetry`, `onBreak`, `onReset` etc.  

There are also some arguments around whether it is a good idea to allow the reconfiguration of what a policy _handles_ at runtime  ... think fragility risks from unexpected emergent behaviour (Somebody changes the config so the app _stops_ handling a certain exception during runtime: what's the effect on the downstream code? etc). ... And how does this play with testable code? 

Where configuration-from-config (and reconfiguration-without-redeploy) could really shine, though, is in re-configuring the numeric parameters of policies.  Could be a major benefit to be able to tweak, _on the fly_, _in production_, the trigger thresholds and break durations of circuit-breakers, the delay between retries etc ... according to real-world behaviour.  This could be achieved by pulling the numeric-parameterisation parts of each policy out into a configuration class, which could be injected (to update the policy) at any time.  Perhaps where we should focus our efforts first on this feature?
 
In sum, I'm starting to see this proposal perhaps emerge into two separate (potential) features:

+ the ability to reconfigure the numeric parameters of (all) policies at any time (with perhaps some plugins/separate projects demo-ing how to do this from configs, json etc)
+ a `PolicyRegistry` for those who want to maintain a bank of (named) policies in a Registry, perhaps [applying them by attribute](https://github.com/App-vNext/Polly/issues/87) as @eaba suggested (but without the suggestion at this stage that we can fully configure that PolicyRegistry from config)

Thoughts, anyone?

**Comment by pvmraghunandan** [comment] 2016-07-07 19:27
"major benefit to be able to tweak, on the fly, in production, the trigger thresholds and break durations of circuit-breakers". This is exactly what we are looking for. And as you said, it is difficult to handle events like onBreak.. But we are thinking to provide some sort of configuration like {Type, PropertyName, PropertyType,  Accepted Values}. Eventhough its pretty much easy to code for example handling status in WebException, can we think on some optimized way so that we don't do much reflection and doesn't have performance benefits.

**Comment by reisenberger** [comment] 2016-07-14 07:29
>we are thinking to provide some sort of configuration like 
>{Type, PropertyName, PropertyType, Accepted Values}. 

@pvmraghunandan Was this with the types and properties of exceptions (or results) handled by the policy in mind? 

It's likely that the core Polly team wouldn't have time to look at this for the next couple of months, by the way, while the focus is on the new resilience features.

**Comment by pvmraghunandan** [comment] 2016-07-18 07:08
@reisenberger  The type and properties are used during HandleException and HandleRetry delegate being called. For now we have taken simple approach of only having exception types as configurable instead of introducing bit complexity and reflection.

**Comment by reisenberger** [comment] 2017-06-11 21:35
Noting that @brunolauze also had good proposals for this [here](https://github.com/App-vNext/Polly/issues/141#issuecomment-237036724)

**Comment by reisenberger** [comment] 2018-01-02 09:59
Closing as duplicate of / in favour of the similar ideas in #143

**Closed by reisenberger** 2018-01-02 09:59 UTC
Labels: configuration feature
