### ISSUE TITLE
Decorrelated jitter does not jitter well

### ISSUE THREAD

**Issue by george-polevoy** [App-vNext/Polly#530] opened 2018-11-09 11:28 UTC
**Summary: Jitter the retry delays to achieve low concurrency**

<br/>
<br/>

**I'm trying to use the suggested "decorrelated jitter" strategy**  

![jittering](https://user-images.githubusercontent.com/2792885/48259864-6fc8f380-e42a-11e8-9b9d-2311ce3b3e5d.PNG)

In my experiment, the [suggested decorrelated jitter](https://github.com/App-vNext/Polly/wiki/Retry-with-jitter) does not achieve what it supposed to.

First, `new Random()` is not quite random, when it comes to reducing concurrency.
You can get multiple instances with the same seed, if many retries are issued simultaneously.

Following code achieves much lower concurrency and better distribution.
In the attached screenshot you can see that the 'advanced' graph has much lower maximum and smoother distribution, which is highly desired to avoid concurrency spikes.

```
IEnumerable<TimeSpan> DecorrelatedExponent()
{
    var r = new Random(Guid.NewGuid().GetHashCode());
    for (var softAttemptCount = 0.0; softAttemptCount < 4; ) {
        softAttemptCount += r.NextDouble() * 2;
        yield return TimeSpan.FromSeconds(
            Math.Pow(2, softAttemptCount) * random.NextDouble());
    }
}

```

**Comment by reisenberger** [comment] 2018-11-10 16:10
Thank you @george-polevoy for diving deeper on this than I had time to and for sharing that with the community, this is super interesting.  The [decorrelated Jitter strategy quoted](https://github.com/App-vNext/Polly/wiki/Retry-with-jitter#more-complex-jitter) came from that [AWS team research](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/), definitely open to investigating different options.

First, could you say what the axes on the graphs represent? <sup>(A guess ... the number of instances (vertical) of a specific delay of some-or-other timespan (horizontal) when averaged over 100000 iterations of the algorithm ... but you can state precisely? )</sup>

Second, would you be happy to share the test code which generated the results? (maybe in a ZIP or github gist). It would be great for you/ I/ others to be able to validate, and to build further on your results and explore how tweaking the algorithms affects outcomes.   

>Following code achieves much better distribution

I am definitely seeing in your graphs that the green line is much more smoothly distributed than the yellow line as generated in the tests! :+1: 

>Following code achieves much lower latency

I want to be sure I have understood what we mean by this.  Do we mean that the average delay that the algorithm _chooses_ to introduce before retrying (average perhaps in some sense of area under graph/percentiles), is lower?  Or do we mean (for example) that the average overall time to achieve success is less, for each algorithm pitted against a failed system which recovers after some random amount of time?  

It would be really interesting to be able to build on your experiments (if they do not cover this already) to be able to analyse the dimensions of overall latency to achieve success, combined with number of calls made to achieve success.  

Thank you again for sharing this with the community!

**Comment by grant-d** [comment] 2018-11-10 16:36
George, would you mind trying your experiment with the `Random` taken out of the method and rather declared as a `private static readonly Random` on the class? That way we share it across concurrent retries so won't get the same seed. It would be interesting to see how the graph compares.

**Comment by george-polevoy** [comment] 2018-11-12 11:48
@reisenberger Dylan, sure there was a mistake. It was concurrency that is improved, not latency, I've updated the initial issue.

The vertical axis represents number of experiments. Virtual massive retry event of simultaneous 100000 requests could result in concurrency splash, which is illustrated. If I try to graph fewer experiments, the graph is just too noisy. I understand that the number of experiments is irrelevant, so it would be usefult to factor it out, and display just some normalized probability distribution.

I will try to come up with complete benchmark code, so others could explore and experiment.

**Comment by george-polevoy** [comment] 2018-11-12 19:39
@grant_d Random is not thread safe, I'm afraid, and I'm using a random seed fron Guid.GetHashCode, which is an alternative to using a thread local variable.

**Comment by grant-d** [comment] 2018-11-12 20:09
George the issue is that your source of randomness is not random - see my notes above, and see the first code snippet [here](http://www.yoda.arachsys.com/csharp/miscutil/usage/staticrandom.html).
Guid.GetHashCode() is _not_ random.
You are correct that I forgot the `[ThreadStatic]` attribute. Code sample updated.

**Comment by reisenberger** [comment] 2018-11-12 22:58
Thanks to both of you @george-polevoy and @grant-d for progressing this!  I haven't had much time on this thread but note that:

+ the [current .NET core implementation](https://github.com/dotnet/corefx/blob/62c70143cfbb08bbf03b5b8aad60c2add84a0d9e/src/Common/src/CoreLib/System/Random.cs#L118-L151) seems to use a static global instance of `Random` to provide random seeds for `[ThreadStatic]` instances of `Random`, which in turn are used to fulfil `new Random()` called on any thread.  This approach was _supposed_ (according to various posts by Jon Skeet and Stephen Toub; will try to find links again) ... supposed to improve randomisation behaviour for `new Random()` called on any thread.  
+ However, [Jon Skeet seems to have rowed back from that](https://stackoverflow.com/a/25448166/) and the [latest .NET Framework recommendation](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#the-systemrandom-class-and-thread-safety) is to use a single instance application-wide (for maximum randomness), but with fine-grained locking or similar (because a single instance is not thread-safe for simultaneous access from multiple threads).  
+ There are [discussions on changing the algorithm for .NET Core/Standard](https://github.com/dotnet/corefx/issues/12746), but no changes seem to have landed yet, afaics.

So: Should we just be following the recommendations [here](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#avoiding-multiple-instantiations) and [here](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#the-systemrandom-class-and-thread-safety)?

(V happy for further clarifications/corrections, as the above was just based on some brief reading!)

**Comment by george-polevoy** [comment] 2018-11-13 08:41
@grant-d Randomness is not an issue here. I will share code for you to verify. My computations are now single threaded and deterministic, using a fixed random seed and a shared Random instance, not using Polly. Also, system clock issues can be ruled out, because this is just purely math integration based on deterministic pseudorandom sequence. The entire computation does not depend on runtime issues of NET, it's computed offline. It's just a math routine. I'm computing the delay sequence function itself using virtual regular time intervals.

**Comment by george-polevoy** [comment] 2018-11-13 23:16
I see the problem with your code.

In addition to min(cap, ...) that AWS team suggested in their blog, you've also added max(seed, ...).

Say we have 100 requests failed at time t0.
Seed = 1s, and max=3s.

What is the probability of scheduling a request at time t0 + 1s? It's 1/3, because all of the values lower than t0+1s clamp. So you've got aprox. 25 requests at exact timing: t0 + 1s.
All of the other requests will be distributed uniformly. The next clamp will appear at t0 + 2s, and concurrency will be lower (1/3^2 = 1/9 = aprox. 9) at exact timing t0 + 2s.

That completely explains the fist two spikes on the graph, which are clearly seen.

I've examined the code on the AWS blog, and they have slightly different thing. They use random_between, which is not max(something, random.NextDouble).
Random between should be a linear mapping, not limiting with Max.
Replace it with RandomBetween(x, y) = x + r.NextDouble() * (y-x) and the problem is gone.

I will follow up with the modelling code i'm using.

**Comment by grant-d** [comment] 2018-11-13 23:19
Agree - my code has a slightly different implementation to the wiki too, though I am still refining it. I am curious to compare it with yours, please do post it as soon as you are ready.

**Comment by grant-d** [comment] 2018-11-14 01:16
For reference, here's my code:
```csharp
            double range = MaxDelay.TotalMilliseconds - MinDelay.Milliseconds;
            for (int i = 0; i < delays.Length; i++) 
            { 
                double ms = range * _random.NextDouble(); // Range
                ms += MinDelay.TotalMilliseconds; // Floor 
                ms = Math.Min(ms, MaxDelay.TotalMilliseconds); // Ceiling (might be redundant)

                delays[i] = TimeSpan.FromMilliseconds(ms); 
            }
```

**Comment by reisenberger** [comment] 2018-11-15 07:55
Thanks both @george-polevoy @grant-d ! Would be great to see graphs  of the distributions of generated by the revised algorithms.

**Comment by reisenberger** [comment] 2018-11-16 23:18
Again, thank you both  @george-polevoy @grant-d .

@george-polevoy I think [your analysis here](https://github.com/App-vNext/Polly/issues/530#issuecomment-438475057) is exactly correct.  Thank you for spotting the (now obvious, yes) flaw in the algorithm [here at time of writing](https://github.com/App-vNext/Polly/wiki/Retry-with-jitter#more-complex-jitter).

@grant-d [The version in your PR](https://github.com/App-vNext/Polly/blob/b4bffc42988297e3d492865f6eb847e2bcf112ab/src/Polly.Shared/Duration/DecorrelatedJitterBackoff.cs#L70-L79) (for which many thanks) also matches this analysis and the AWS algorithm, I believe.  Thanks for all the work on this and the PR!

**Comment by reisenberger** [comment] 2018-11-16 23:46
Finally, @george-polevoy : are you happy now with the behaviour of the AWS algorithm following the corrections you have introduced? (for which many thanks!). Or are there aspects of the 'advanced' algorithm [from your original post](https://github.com/App-vNext/Polly/issues/530#issue-379125479) you think still worth considering?  I did dive deeper into the advanced algorithm - came up with a bunch of further questions - but won't lengthen this unless you are also interested in pursuing.

It would be awesome to see how the "fixed" AWS algorithm looks also in your graphs.

**Comment by reisenberger** [comment] 2018-11-17 07:13
Alternatively, @grant-d , @george-polevoy , we could eliminate the [upper-end-bunching](https://github.com/App-vNext/Polly/issues/530#issuecomment-439559880) by modifying the latest implementation like this:

            double ms = MinDelay.TotalMilliseconds;
            for (; i < retryCount; i++)
            {
                double ceiling = Math.Min(MaxDelay.TotalMilliseconds, ms * 3);
                ms = _random.Uniform(MinDelay.TotalMilliseconds, ceiling);

                yield return TimeSpan.FromMilliseconds(ms);
            }

Is this worth modelling (to confirm smoothness) in George's graphing system? Can anyone see disadvantages?  One implication is that when `ms * 3 > MaxDelay.TotalMilliseconds`, there is no longer any backoff.  It speaks to the same problem [previously discussed](https://github.com/App-vNext/Polly/issues/530#issuecomment-439559880), that users do need to choose `MaxDelay` significantly proportionally larger than `seed`.  However, that lack of backoff may be preferable to the upper-end bunching.

**Comment by reisenberger** [comment] 2018-11-18 09:56
This revisits my [previous comment](https://github.com/App-vNext/Polly/issues/530#issuecomment-438059213) on implementations of `System.Random`, to provide promised references and clarify for the sake of accuracy and future readers: 

>the [current .NET core implementation](https://github.com/dotnet/corefx/blob/62c70143cfbb08bbf03b5b8aad60c2add84a0d9e/src/Common/src/CoreLib/System/Random.cs#L118-L151) seems to use a static global instance of Random to provide random seeds for [ThreadStatic] instances of Random, which in turn are used to fulfil new Random() called on any thread. This approach was supposed (according to various posts by Jon Skeet and Stephen Toub; will try to find links again) ... supposed to improve randomisation behaviour for new Random() called on any thread.

References: [post by Stephen Toub](https://blogs.msdn.microsoft.com/pfxteam/2009/02/19/getting-random-numbers-in-a-thread-safe-way/); [Jon Skeet 1](https://codeblog.jonskeet.uk/2009/11/04/revisiting-randomness/); [Jon Skeet 2](https://stackoverflow.com/a/25448166).  

>There are [discussions on changing the algorithm for .NET Core/Standard](https://github.com/dotnet/corefx/issues/12746), but no changes seem to have landed yet, afaics.

The latest .NET framework and .NET core implementations do in fact differ, because the [.NET Framework 4.7.2 implementation](https://referencesource.microsoft.com/#mscorlib/system/random.cs,53) still (!- for backward compatibility presumably) has `Environment.TickCount` as a seed `new Random()`, whereas .NET Core has [moved on to a chained-RNGs approach](https://github.com/dotnet/corefx/blob/62c70143cfbb08bbf03b5b8aad60c2add84a0d9e/src/Common/src/CoreLib/System/Random.cs#L118-L151).  (The discussions on [changing the algorithm](https://github.com/dotnet/corefx/issues/12746) were around the Knuth algorithm vs others, rather than the seed.)

>However, [Jon Skeet seems to have rowed back from [the chained-RNG approach]](https://stackoverflow.com/a/25448166/) and the [latest .NET Framework recommendation](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#the-systemrandom-class-and-thread-safety) is to use a single instance application-wide (for maximum randomness), but with fine-grained locking or similar (because a single instance is not thread-safe for simultaneous access from multiple threads).

The recommendation I linked pertains to .NET Framework not .NET Core.  However, in targeting .NET _Standard_, Polly of course can still  (as is well known) be consumed by builds against [.NET Framework 4.5 and up](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support). So we should still take account of the [.NET Framework recommendation](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#the-systemrandom-class-and-thread-safety) if for jitter we are targeting maximum randomness.

---

Broadly, it is essential to make `Random` *thread-safe*, and these discussions embrace two different approaches to that which exhibit different trade-offs:

+ a fine-grained-lock on a single static instance of `Random`
  - emphasizes improved randomisation but introduces fine-grained locking (_per acquisition of each random number_), which could affect perf in high-concurrency scenarios.  
  - recommend for Polly's Jitter use case: improved randomisation is important, to avoid spikes; delay due to lock contention is insignificant in the context of introducing jitter delays and executions which have already failed anyway.
+ a chained-RNGs approach with thread-safety achieved by `[ThreadStatic]` or `ThreadLocal<T>`
  - doubts over its randomisation credentials being as strong as the preceding approach, but improved perf in high-concurrency scenarios due to no locking.
  - recommend for Polly's [chaos-injection use case](https://github.com/App-vNext/Polly/pull/508); we would want randomised chaos-injection to have absolutely minimal drag on executions which _weren't_ randomly selected for chaos injection, so avoidance of locking is preferred; that consideration is more important than how randomly the chaos-impacted executions are selected.

**Comment by george-polevoy** [comment] 2018-11-20 13:54
@reisenberger Algorithm by AWS also has a flaw. On my graphs it looks smoother, but still has spikes, because it's not truly decorrelated.

@grant-d The problem with clamping using Min Max is that it ruins randomness, flooding the distribution with some constants. As for the API guarantees, you can use math to proof the MAX and MIN. For ex. max recovery interval for retry is a sum of geometric progression, not matter if you randomize inside, if only limited range random variable does not participate in any asymptotic math function such as 1/x.

My graphing framework turned to be very useful to analyze the problem. I will share it as I promised as I clean up the code.

Currently busy preparing for my DotNext talk this week.
I will follow up next week. I've put substantial effort into exploring this, and I will make sure we use strong math and also we will have good visual proof of what's happening in our formulas.

**Comment by reisenberger** [comment] 2018-11-24 12:14
Again, big thanks both @george-polevoy , @grant-d for everything you are contributing on this. Looking forward @george-polevoy to seeing more.

**Comment by george-polevoy** [comment] 2018-11-26 18:12
I have few more results for you to consider.
![image](https://user-images.githubusercontent.com/2792885/49033131-6deb8800-f1bf-11e8-9f6c-dfd02e11bc0d.png)

https://gist.github.com/george-polevoy/c0c36c3c22c9c1fe67821b1d8255413a

**Comment by grant-d** [comment] 2018-11-26 18:39
Very nice, I like how clear the AWS clamping problem is (glad we fixed that).
Is your aim with the other algorithms to include them in the library? If so I have no problem with that, I think `softexp` is particularly interesting.

**Comment by george-polevoy** [comment] 2018-11-26 19:01
I think "soft exp, soft delay X" family looks best to me. It keeps exponential property, has reasonably low peak, low at start, and a hard limit of $2^(n+1) + 1$
But most importantly, it reduces the probability of sharp peaks.

I have another framework which can be used to assess concurrency issues.
Stochastic algorithms approach is different from deterministic reasoning, no need to clear the interval from 0 to the first retry completely, because you don't know the exact time of start of the transient failure condition anyway, why not to try during that interval, if it helps distribute retries evenly?

**Comment by grant-d** [comment] 2018-11-26 23:39
> Stochastic algorithms approach

Sorry George, I don't understand what you are getting at in the last paragraph, would you mind explaining again?

**Comment by reisenberger** [comment] 2018-11-27 07:13
Huge thanks @george-polevoy . Now digging in to this. (Bear with me if it takes a few days to respond; everything I do for Polly happens separately from paid-work ...)

**Comment by george-polevoy** [comment] 2018-11-27 10:40
@grant-d Yes, I mean immediately.

Instead of minimum delay, there could be _half decay_ period parameter, which is more meaningful for the exponential function. This would be a point in time when probability drops to 1/2.
Exponential property guarantees that the amount of requests going before the _half decay_ would equal to the amount of request coming after (green and purple on the graph have the same area).

https://www.desmos.com/calculator/qmqaapanvc

![image](https://user-images.githubusercontent.com/2792885/49076352-da12ce00-f249-11e8-8a99-e53561154ba9.png)

**Comment by reisenberger** [comment] 2018-12-02 15:29
@george-polevoy I've run out time to dive into these in depth this week, due to the numb, but wanting to get to this soon. Thanks!

**Comment by reisenberger** [comment] 2018-12-14 19:19
@george-polevoy Again, thank you. I now digested the algorithm math and [simulation basis](https://gist.github.com/george-polevoy/c0c36c3c22c9c1fe67821b1d8255413a), very nice.  Nice use of the natural shape of `tanh` to smooth just the initial part of 'soft exp soft delay' ;-}

See the [comment on @grant-d 's PR](https://github.com/App-vNext/Polly/pull/536#issuecomment-446862770): we could pull some of the new algorithms here into a separate `Polly.Contrib` package? (if you are willing), together with what @grant-d has put together for other sleep duration strategies.

A remaining thought: it could be useful to understand for the new algorithms where the 50th percentile (say) falls - or see the shape of the graph as a whole - for try 1, try 2, try 3, try 4, _separately_ ... to see how those 50th percentiles (/or the distribution) progresses, with increasing tries. 

For example, looking at the graph (and formula) for 'exp jittered (Shifted)', it seems clear the 50th percentiles likely fall with the apex of each peak. But for 'soft exp, soft delay', we probably need to mine some data (/see a graph-per-try) to get a clear idea of how the 50th percentiles fall and progress. 

I've worked out how to amend your simulation code to generate this, so I can do, but if it's quick for you/you feel like pulling that out, say for the 'soft exp, soft delay 3' case, that would be useful to see.

**Why?** Mostly we have focused on how to make the distribution smooth, to fair-schedule retries to reduce contention, perhaps with the background assumption that the underlying system is basically healthy.  But I want to keep also in focus the dimension that the retries should happen with increasing delay, for the case of a system which is unhealthy/failing/struggling under load.  For unhealthy systems, it can be important that later retries significantly back off - to reduce the potential for retries creating a self-DDOS attack.  (Sure, the problem is stochastic, but broadly speaking, by the time fourth retries (say) start kicking in, we will be quadrupling the load.)  (And of course, there are other techniques to avoid this, like circuit-breaking on too many failures, but as a gen principle it's helpful for retries to have increasing back off.)  So, I would just like to dig into and be sure we understand this aspect - the _degree_ of increasing backoff emerging from the new algorithms - before we go to the Polly public with a recommendation.

Thanks again, @grant-d , @george-polevoy , for everything we are doing on this.

**Comment by reisenberger** [comment] 2018-12-30 11:17
@george-polevoy @grant-d  I adapted George's simulation code (for which huge thanks) to graph up the retry interval distribution for individual tries separately.  I am happy that the "soft exp, soft delay" function does create clearly increasing backoff as try number progresses. For example, for "soft exp, soft delay 3".  

#### Soft exp, soft delay 3: Distribution of retry intervals for try 0

![image](https://user-images.githubusercontent.com/9608723/50546668-78b49500-0c23-11e9-9942-8283125561ca.png)

#### Soft exp, soft delay 3: Distribution of retry intervals for try 1

![image](https://user-images.githubusercontent.com/9608723/50546682-ac8fba80-0c23-11e9-9c15-4a4bb3bfeea2.png)

#### Soft exp, soft delay 3: Distribution of retry intervals for try 2

![image](https://user-images.githubusercontent.com/9608723/50546691-d77a0e80-0c23-11e9-99e7-21fd1a7adcca.png)

#### Soft exp, soft delay 3: Distribution of retry intervals for try 3

![image](https://user-images.githubusercontent.com/9608723/50546703-fd071800-0c23-11e9-83f2-9d3b2f558401.png)

**Comment by reisenberger** [comment] 2019-03-02 14:02
Thanks again @grant-d and @george-polevoy for the great investigation into jitter strategy.

Polly v7 has now launched, and we have a [Polly-Contrib](https://github.com/Polly-Contrib).  I propose - if you are in agreement - we take @grant-d 's PR #536 and your awesome jitter work here @george-polevoy, and make a Polly.Contrib repo [Polly.Contrib.WaitAndRetryStrategies](https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetryStrategies) to publish it.  The repo would give you:

+ full 'write' rights to manage the repo, make/merge PRs etc
+ isolated box (not mixed with anyone else's contrib; only you or people we invite have rights)
+ a [template](https://github.com/Polly-Contrib/Polly.Contrib.BlankTemplate) with [solution/projects](https://github.com/Polly-Contrib/Polly.Contrib.BlankTemplate/tree/master/src) correctly set up to reference latest Polly and build targets
+ and a [full build](https://github.com/Polly-Contrib/Polly.Contrib.BlankTemplate/blob/master/build.cake) ready to publish your nuget package which will correctly reference Polly.

(ie you can basically just rename from the template, place your code in, and good to go!)

If this sounds good, I can clone to make you a [Polly.Contrib.WaitAndRetryStrategies](https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetryStrategies).

(Polly.Contrib also allows me to "get out of the way" and allow contributors such as yourselves to publish these contributions without being blocked on feedback or discussion about exact shape of the API - although I'm still v much there to support if needed. And evolve, eg @george-polevoy , if you want to add something later with half-life/half-decay parameter.)

Also, if we go the contrib route, I would still want to feature this as strongly out from the main Polly, ie to replace/update the [wiki jitter information](https://github.com/App-vNext/Polly/wiki/Retry-with-jitter) and reach out to your contrib from there and from the [readme](https://github.com/App-vNext/Polly#retry).

Let me know what you think.

---

@george-polevoy Also, I did some work with Cesar de la Torre around resilience in the Microservices sample app couple of years ago, some of it ended up in [this ebook](https://blogs.msdn.microsoft.com/cesardelatorre/2017/05/10/free-ebookguide-on-net-microservices-architecture-for-containerized-net-applications/), parts of which are also online [here](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly).  Assuming we publish your jitter strategy to Polly.Contrib.WaitAndRetryStrategies, we can also suggest a PR to update that Microsoft jitter documentation to reference your better strategy.

**Comment by grant-d** [comment] 2019-03-02 15:05
That sounds like a great idea, thanks for thinking through it in such detail. The only request I'd make is to that the name is a mouthful, I wonder if there is something more concise.  `Polly.Contrib.WaitRetry` or `.Backoff` or the like

**Comment by grant-d** [comment] 2019-03-02 15:35
Appreciate your humbleness but your involvement is critical to he success of contrib. My submission is much improved after your input. So you 'getting out the way' is not on my priority list.

**Comment by reisenberger** [comment] 2019-03-03 15:08
No worries @grant-d. We've wanted to get the Polly.Contrib in place for a while, so that users can build additions without the Polly team having to sign off every decision, it gives everyone (me too) a bit more flexibility.  The retry strategies are quite a small case (could go either way), but partic the option to keep refining the jitter math point to Contrib.

**Comment by reisenberger** [comment] 2019-03-03 15:11
I am good with `Polly.Contrib.WaitAndRetry` or open other suggestions.

To know: The choice becomes the namespace ie `namespace Polly.Contrib.WaitAndRetry` and thus `using Polly.Contrib.WaitAndRetry`

**Comment by reisenberger** [comment] 2019-03-18 08:49
I've created the [Polly.Contrib.WaitAndRetry repo](https://github.com/Polly-Contrib/WaitAndRetry) and am sending you both (@grant-d @george-polevoy) invites to the [Polly-Contrib organization](https://github.com/Polly-Contrib).

@george-polevoy I'd suggest we use your 'soft exp, soft delay X' algorithm as the best jitter candidate so far (unless you think different).  I've invited you to the repo (ie you get write-access) so that you can continue to make changes/suggestions to refine the jitter algorithm further _if you want_; it's been awesome to have all your great input so far.

@grant-d Are you good to pull the conclusions we came to on this/and other thread into the new repo?  You can pull down a zip from [Polly.Contrib.BlankTemplate](https://github.com/Polly-Contrib/Polly.Contrib.BlankTemplate), and just rename/add to form the new Polly.Contrib.WaitAndRetry, then upload back up to Polly.Contrib.WaitAndRetry.  After you accept the Polly-Contrib invite you have write rights on the repo.   

Let me know when there's a nuget publish candidate and we can figure out the publish step (publish under a Contrib org or individually)

Thanks hugely to you both for the awesome contribution!

Let me know if any questions/anything I can help with.

**Comment by grant-d** [comment] 2019-04-04 03:05
Initial commit here : https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry/pull/2

I just saw your note above about the template - I will retrofit it suitably.

**Comment by reisenberger** [comment] 2019-08-28 07:56
@george-polevoy Are you happy if we include your 'soft exp, soft delay X' algorithm in the [Polly.Contrib.WaitAndRetry](https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry) repo?

**Comment by george-polevoy** [comment] 2019-08-30 10:46
@reisenberger Sure

**Comment by reisenberger** [comment] 2019-09-01 09:33
PR made to pull the new jitter formula into Polly.Contrib.WaitAndRetry : https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry/pull/11

**Comment by reisenberger** [comment] 2019-09-16 22:58
Closing. The new jitter formula is now published to nuget as part of [Polly.Contrib.WaitAndRetry](https://www.nuget.org/packages/Polly.Contrib.WaitAndRetry), and documented [in the readme of that project](https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry#new-jitter-recommendation) with references back to here.

Thanks to all @george-polevoy @grant-d for raising the issue and clarifying the math and logic so strongly.

[Polly wiki on jitter](https://github.com/App-vNext/Polly/wiki/Retry-with-jitter) similarly updated.

**Closed by reisenberger** 2019-09-16 22:58 UTC
Labels: bug, enhancement

**Comment by onemvictor** [comment] 2025-03-12 12:32
> Thanks to both of you [@george-polevoy](https://github.com/george-polevoy) and [@grant-d](https://github.com/grant-d) for progressing this! I haven't had much time on this thread but note that:
> 
>     * the [current .NET core implementation](https://github.com/dotnet/corefx/blob/62c70143cfbb08bbf03b5b8aad60c2add84a0d9e/src/Common/src/CoreLib/System/Random.cs#L118-L151) seems to use a static global instance of `Random` to provide random seeds for `[ThreadStatic]` instances of `Random`, which in turn are used to fulfil `new Random()` called on any thread.  This approach was _supposed_ (according to various posts by Jon Skeet and Stephen Toub; will try to find links again) ... supposed to improve randomisation behaviour for `new Random()` called on any thread.
> 
>     * However, [Jon Skeet seems to have rowed back from that](https://stackoverflow.com/a/25448166/) and the [latest .NET Framework recommendation](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#the-systemrandom-class-and-thread-safety) is to use a single instance application-wide (for maximum randomness), but with fine-grained locking or similar (because a single instance is not thread-safe for simultaneous access from multiple threads).
> 
>     * There are [discussions on changing the algorithm for .NET Core/Standard](https://github.com/dotnet/corefx/issues/12746), but no changes seem to have landed yet, afaics.
> 
> 
> So: Should we just be following the recommendations [here](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#avoiding-multiple-instantiations) and [here](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#the-systemrandom-class-and-thread-safety)?
> 
> (V happy for further clarifications/corrections, as the above was just based on some brief reading!)


I understand this is old thread. But how to ensure randomness in a multi-process scenario, like multiple instances of a same microservice running?

**Comment by martincostello** [comment] 2025-03-12 12:57
Both the built-in jitter in Polly.Core v8 and the code being linked to use the `Random` class, which is initialized with [a default seed that is an implementation detail of .NET](https://learn.microsoft.com/dotnet/api/system.random.-ctor#system-random-ctor). If you want to create your own seed, you can provide your own `Random` instance. If you want to pay a small performance penalty for a cryptographically-secure random number, you could use [`RandomNumberGenerator` class](https://learn.microsoft.com/dotnet/api/system.security.cryptography.randomnumbergenerator) to get your random numbers instead.
