### ISSUE TITLE
PolicyRegistry constructor is no longer public

### ISSUE THREAD

**Issue by hswami** [App-vNext/Polly#719] opened 2019-11-09 15:22 UTC
**Summary**: 
The constructor for PolicyRegistry is no longer public. All the documentation around usage of PolicyRegistry contains code like "new PolicyRegistry()". But v3 of the Nuget package does not expose the constructor as a public constructor. So how should is one expected to setup PolicyRegistry? Either code or docs have a bug.

**Comment by reisenberger** [comment] 2019-11-09 16:31
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Likely duplicate of #584, already fixed in 585. Adding a direct reference to Polly v7.0.2 (or any later version) will fix this. Apologies for the short reply; I am on travel. 
>v3 of the Nuget package
Could you confirm if that refers to Polly.Caching.IDistributedCache? Thank you.

**Comment by reisenberger** [comment] 2019-11-13 18:54
Prevented the issue recurring when consuming `Polly.Caching.Distributed` latest version, by releasing [Polly.Caching.Distributed v3.0.1](https://www.nuget.org/packages/Polly.Caching.Distributed/3.0.1)

**Closed by reisenberger** 2019-11-13 18:54 UTC
Labels: bug fix
