### ISSUE TITLE
[Feature request]: Conditionally set log levels for specific resilience policy

### ISSUE THREAD

**Issue by GordonSo** [App-vNext/Polly#2090] opened 2024-05-01 11:27 UTC
### Is your feature request related to a specific problem? Or an existing feature?

Currently, when the rate-limiting threshold is reached, Polly would log an error log:
```
Resilience event occurred. EventName: ‘“OnRateLimiterRejected”‘, Source: ‘“url/RateLimit”/“url/RateLimit”/“ratelimited”‘, Operation Key: ‘“operation_key”’, Result: ‘null’
```

This is an expected behaviour in our use case, and we would like to suppress the log, without suppressing all other logs from the library. 

Our current solution is to bump the log level for the entire to be "warning" -> "fatal" at the .net logging configuration e.g.
![image](https://github.com/App-vNext/Polly/assets/4214928/274d51d0-eb86-4437-8fef-22301e198a9d)

The request would be to suppress only the "OnRateLimiterRejected" to "warning".

### Describe the solution you'd like

We found that the log is hardcoded to be ResilienceEventSeverity.Error, here:
https://github.com/App-vNext/Polly/blob/main/src/Polly.RateLimiting/RateLimiterResilienceStrategy.cs#L61

The initial idea is to extend the policy, so we can initialise the pipeline with an optional parameter for the overriding `log.level`. 

If this option sounds feasible, we can start digging deep and maybe help raise a PR...

**Comment by martincostello** [comment] 2024-05-01 11:31
Duplicate of #1859, which there is a PR open for in #2072.

**Closed by martincostello** 2024-05-01 11:31 UTC
Labels: feature suggestion
