### ISSUE TITLE
PollyTalk.org return Internal Server Error

### ISSUE THREAD

**Issue by vdekercd** [App-vNext/Polly#1551] opened 2023-09-05 16:42 UTC
**Summary**: 

PollyTalk.org return Internal Server Error

**Expected behavior**: 

The PollyTalk site works

**Actual behaviour**:

PollyTalk.org return Internal Server Error

**Steps / Code to reproduce the problem**: 

[Go to PollyTalk site](https://www.pollytalk.org)

**Comment by martincostello** [comment] 2023-09-05 17:59
Duplicate of #1256.

**Closed by martincostello** 2023-09-05 17:59 UTC

**Comment by vdekercd** [comment] 2023-09-05 18:01
My bad! Sorry.
