### ISSUE TITLE
Half Open State Handling

### ISSUE THREAD

**Issue by pvmraghunandan** [App-vNext/Polly#254] opened 2017-06-05 10:24 UTC
During Half Open State, as per general recommendation, below is guideline

>A limited number of requests from the application are allowed to pass through and invoke the operation. If these requests are successful, it's assumed that the fault that was previously causing the failure has been fixed and the circuit breaker switches to the Closed state (the failure counter is reset). If any request fails, the circuit breaker assumes that the fault is still present so it reverts back to the Open state and restarts the timeout timer to give the system a further period of time to recover from the failure. 

(Source : https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker)

But, currently seeing the way Polly is implemented, it sends all requests (if we get 1000 requests after half-open) and acts upon first result of request and change state to Closed/Open. Shouldn't we apply same metric calculation (in case of advanced) and limit requests probably via different configuration? Pasting switch/case below

```
 public override void OnActionFailure(DelegateResult<TResult> outcome, Context context)
 {
     using (TimedLock.Lock(_lock))
     {
         _lastOutcome = outcome;

         switch (_circuitState)
         {
             case CircuitState.HalfOpen:
                 Break_NeedsLock(context);
                 return;
				
             default:
                 throw new InvalidOperationException("Unhandled CircuitState.");
         }
     }
 }
```

**Comment by reisenberger** [comment] 2017-06-05 17:51
@pvmraghunandan I am currently on travel and will respond to this in two or three days' time.

**Comment by reisenberger** [comment] 2017-06-08 06:17
Thanks @pvmraghunandan for this.

The possibility of a request stampede during half-open state was [identified recently](https://github.com/App-vNext/Polly/issues/216) and we believe [fixed in v5.0.5](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md#505).  If you think this is still an issue (after upgrading to >=v5.0.5 if necessary), please let us know.  [Here is the code](https://github.com/App-vNext/Polly/blob/73fc38029f52d2e1bfa6f4b03bcb1e12d8c78065/src/Polly.Shared/CircuitBreaker/CircuitStateController.cs#L131) that enforces only one new trial call per break duration.  Multiple requests that are already in flight when the circuit transitions to half-open state can of course not be prevented from still returning during the half-open state (discussion: #217, #218).

We've had discussion lately of a more-refined metric for transitioning out of half-open state under #239 : latest thinking [here](https://github.com/App-vNext/Polly/issues/239#issuecomment-292710948).  For a [consecutive-count-based breaker](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker) (the case discussed in the [patterns/practices article](https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker)), it seems fairly straightforward.  The [AdvancedCircuitBreaker case](https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker) (the Hystrix circuit-breaker model) is less transparent, though solvable.  Further comment welcome!

**Comment by pvmraghunandan** [comment] 2017-07-17 05:08
@reisenberger I have been quite a busy and didn't get chance to check status on this issue. I will check it out today and update accordingly. Thanks for quick response.

**Comment by reisenberger** [comment] 2018-01-02 16:26
Closing as duplicate of / covered by #239

**Closed by reisenberger** 2018-01-02 16:26 UTC
Labels: duplicate, enhancement
