### ISSUE TITLE
Combining Polly and IServiceProvider

### ISSUE THREAD

**Issue by pekspro** [App-vNext/Polly#813] opened 2020-12-14 16:42 UTC
**Summary: What are you wanting to achieve?**

In my extremely short experience of Polly, I often find myself need to recreate services when something needs to run again. I work in .NET Core and uses EF Core. If I for instance do not recreate a databasecontext things could be left in the change tracker which may have side effects. There may be other ways to deal with this, but recreating feels like the safe approach to me.

So, I think it would be nice if there was a way to combine this.

**What code or approach do you have so far?**  

I have been playing with this a couple of days and have created something that I call "PolicyScope". Here is some code showing how it is used:

```C#
public class LogicTester
{
    public IPolicyScopeBuilder PolicyScopeBuilder { get; }

    public LogicTester(IPolicyScopeBuilder policyScopeBuilder)
    {
        PolicyScopeBuilder = policyScopeBuilder;
    }

    public Task<int> RunWithResult1ServiceAsync(int argument)
    {
        int runCount = 0;

        return PolicyScopeBuilder
            // From PolicyRegistry, get the policy with this name
            .WithPolicy(PolicyNames.AsyncPolicy1)
            // Create a dummy service (named service1 below)
            .WithService<IDummyService>()
            // Run the code and return an int
            .RunWithResultTypeAsync<int>(async service1 =>  
        {

            // This is the code that is executed by the policy. Everytime 
            // service1 is recreated.

            runCount++;

            await service1.DoWorkAsync(argument);

            return runCount;
        });
    }
}
```

And here is a unit test:

```C#
[Fact]
public async Task TestRunWithResult1ServiceAsync()
{
    // Arrange
    Mock<IDummyService> dummyService = new Mock<IDummyService>();

    var policyScopeMock = PolicyScopeMock
                    // Ensure this policy is being asked for
                    .AsyncPolicy(PolicyNames.AsyncPolicy1)
                    // Use the dummy service on execution
                    .WithService(dummyService.Object)
                    // The service should return an int.
                    .WithResultType<int>();

    LogicTester worker = new LogicTester(policyScopeMock.Object);

    // Act
    int result = await worker.RunWithResult1ServiceAsync(5);

    // Assert
    Assert.Equal(1, result);

    //Ensure the policy were asked for and executed once
    policyScopeMock.Verify(Times.Once());
}
```

I hope this explains my idea. But I have some questions.

Is there already a solution for this that could be used? I do not expect to find this inside this project, but maybe someone else has done this. I have looked but have not found any.

Second, is my approach just stupid? I expect it is since I have not found any similar solution :-)

I would like to have some feedback on my approach. It is very opiniated about which frameworks to use. In this case Polly and the `IServiceProvider` in .NET Core. I am also using Moq for unit testing (maybe I do not need that). Feel free to explain why this is a bad idea so I do not waste my time on this :-)

**Comment by martincostello** [comment] 2020-12-23 18:38
Having read your proposal, I don't fully understand what problem you're trying to solve here with regards to Polly itself.

The [`IReadOnlyPolicyRegistry<TKey>`](https://github.com/App-vNext/Polly/blob/master/src/Polly/Registry/IReadOnlyPolicyRegistry.cs) interface(s) provide a way to access previously created policies, which can be registered with DI itself.

The registry is there to provide a way for policies to be reused across requests. Examples of this usage are for circuit-breakers. If you don't reuse them across all your requests then one individual request will likely never hit the configured limits for the circuit breaker to open, making it not behave as intended. Similarly with the bulkhead policy.

If you registered the registry with your DI container and took it as a dependency in your service where you want to use it, it would be scope agnostic and be (re)created as appropriate by the scopes related to the DI container.

Something like this:

```csharp
using var scope = ServiceProvider.CreateScope();

var registry = scope.ServiceProvider.GetRequiredService<IPolicyRegistry<string>>();
var service = scope.ServiceProvider.GetRequiredService<IDummyService>();
var policy = registry.Get<AsyncRetryPolicy>(PolicyNames.AsyncPolicy1);

await policy.ExecuteAsync(() => {
    runCount++;
    await service1.DoWorkAsync(argument);
});

return runCount;
```

Otherwise given the myriad of ways different policy types, async/sync, overloads with different callback arguments etc. Polly and its policies have, trying to build something like you suggest would be too difficult to build while allowing the user to fully use Polly's capabilities. If it only let you do _some_ things, then which ones would be pick to add to it?

Maybe there's something I'm missing from your proposal I've overlooked here, but it seems like something that has too big a scope (no pun intended) to be something _generic_ that would ship with Polly itself. It looks more like something you could build for your application with a more limited scope appropriate to your specific use case using the primitives already available from the DI container and Polly today.

**Comment by pekspro** [comment] 2020-12-24 09:31
Inside `IPolicyScopeBuilder` I do use `IReadOnlyPolicyRegistry<TKey>` to get the policy requested. I should have mentioned this, sorry about that. I am not trying to reinvent something that already exists 😊. This way I hope it supports most features that inside Polly. But again, I do have limited experience with Polly.

Also, I am not trying to support every feature. Just the features I intend to use, and if more works it is just a bonus :-) So I do not think this should ship with Polly, it makes no sense. In best case it might be useful as a separate package that uses Polly.

You are right that there will be several uses cases to support. Policy types I do not think about since `IReadOnlyPolicyRegistry<TKey>` takes care about that. But it still will be a lot of combinations with:

* With and without return value.
* With and without services that could be more than one (some upper limit is needed).
* Async/sync if I will support that, personally I just need async.

And this is tricky. My brain was melting when I did my first experiment with this 😁. But if I could design some good patterns, I think I could solve this with some kind of source generation.

All this said, I am not still sure what to do about this. So far, I have just wondered it there any similar solution. Now I doubt that there is. Spending my own time is probably not worth it. But I think it is an interesting intellectual challenge so maybe I do it anyway 😊

**Comment by pekspro** [comment] 2021-01-05 18:39
I couldn’t resist so I started a little project. I am quite happy with it. If anyone is interested, it is here:

https://github.com/pekspro/PolicyScope

**Comment by martincostello** [comment] 2021-04-11 16:17
Closing as this is now part of your NuGet package: https://www.nuget.org/packages/Pekspro.PolicyScope/

**Closed by martincostello** 2021-04-11 16:17 UTC
