### ISSUE TITLE
Handle exception with none-default constructor

### ISSUE THREAD

**Issue by mehdihadeli** [App-vNext/Polly#969] opened 2022-12-09 20:17 UTC
Hi,
How can I handle exception with none-default constructor?

``` csharp
  public IdentityUserNotFoundException(string email) : base(
      $"IdentityUser with email '{email}' not found.",HttpStatusCode.NotFound)
  {
  }
```

**Comment by martincostello** [comment] 2022-12-09 20:18
Duplicate of #968.

**Closed as not planned** 2022-12-09 20:19 UTC
