### ISSUE TITLE
HttpClientFactory: Can't access a Singleton by DI within Policy [if construction of that Singleton blocks on an async call creating another DI singleton]

### ISSUE THREAD

**Issue by PTEC3D50** [App-vNext/Polly#751] opened 2020-01-30 14:16 UTC
**Summary**: 
When we try to add a dependecy injection as a Singleton and try to use it in a HttpClient's Policy the program freeze. When the dependency injection is set as a Transient it work.

<br/>

**Expected behavior**: 
It must work in both cases.
<br/>

**Actual behaviour**:
Only work when it's set as a Transient
<br/>

**Steps / Code to reproduce the problem**: 
[PollyAndDI.zip](https://github.com/App-vNext/Polly/files/4134313/PollyAndDI.zip)
Change one of the implementation line 31 or 32 between AddSingleton and AddTransient to try.

Code of the Policy Handler : 

```
AddPolicyHandler((services2, request) =>
                Policy.HandleResult<HttpResponseMessage>(r => r.StatusCode == HttpStatusCode.Unauthorized).RetryAsync(1, (response, retryCount) =>
                {
                    //Get string from dependency injection
                    string test = services2.GetService<IEIAuthentication>().RootUrl;
                    Debug.WriteLine(test);
                }));
```

**Comment by reisenberger** [comment] 2020-01-30 18:57
Hi @PTEC3D50 , thanks for raising this. The HttpClientFactory integration with Polly and the DI implementation is owned by the Microsoft team at https://github.com/dotnet/extensions/, so I was expecting to bounce this to them, but I think I have a resolution for you.

The issue in your code sample looks to be caused specifically by the fact that the constructor of that singleton is blocking on async work:

    public class MainApp
    {
        public MainApp(IHttpClientFactory httpClientFactory)
        {
            //Creation HttpClient
            HttpClient httpClient = httpClientFactory.CreateClient("EiHttpClient");
            string url = "https://httpstat.us/401";

            //Launch HttpRequest
            var challengeHttpResponse = httpClient.GetAsync(new Uri(url)).Result; // ** constructor blocking on async work here
        }
    }

Constructors are typically supposed to complete quickly and should not typically block on async work. If you move the async work out of the constructor, as below:

    public class MainApp
    {
        private IHttpClientFactory httpClientFactory;

        public MainApp(IHttpClientFactory httpClientFactory) { this.httpClientFactory = httpClientFactory; }

        public async Task DoWork()
        {
            //Creation HttpClient
            HttpClient httpClient = httpClientFactory.CreateClient("EiHttpClient");
            string url = "https://httpstat.us/401";

            //Launch HttpRequest
            var challengeHttpResponse = await httpClient.GetAsync(new Uri(url));

            Console.WriteLine($"got status code {challengeHttpResponse.StatusCode}");
        }
    }

then you can declare both services as singletons and there is no deadlock:

    services.AddSingleton<MainApp>();
    services.AddSingleton<IEIAuthentication, EIAuthenticationService>();

Attached is a complete ZIP demonstrating that this works: [Issue751_PollyAndDI-fixed.zip](https://github.com/App-vNext/Polly/files/4135574/Issue751_PollyAndDI-fixed.zip)

---

If you have a class to initialize which does depend on loading some async operation to be ready for use, consider the **Asynchronous Initialization Pattern**: move the async work out of the constructor, as [discussed by Stephen Cleary here](https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html).

---

Knowing the HttpClientFactory code, I suspect this is an emergent behaviour of the DI more generally, rather than being specific to the HttpClientFactory and Polly combination (although I haven't had time to put together an example to prove this).

**Comment by reisenberger** [comment] 2020-02-03 07:28
I step-debugged into the source code for [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/) and found what I believe to be the cause of the deadlock triggered by your original code.

Microsoft.Extensions.DependencyInjection [takes out a lock](https://github.com/dotnet/extensions/blob/32cc8162ff38356b293611138d361f757a62e025/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs#L82) when the DI resolves a singleton (or scoped service for any given scope).  The DI code checks whether the singleton (or instance for that scope) has already been generated and cached, and if not, invokes the constructor and caches the result. The lock is used to ensure only one instance (per scope) is created.

This sequence appears to cause the deadlock (when both `MainApp` and `IEIAuthentication` are configured as singleton via `services.AddSingleton<T>()`):

1. The DI takes out a lock to ensure a singleton of `MainApp`, and invokes the `MainApp` constructor.
2. The `MainApp` constructor successfully retrieves the `EiHttpClient`-named-client configuration from HttpClientFactory.
3. The `MainApp` constructor then executes through `httpClient.GetAsync(new Uri(url))` with a call which invokes the configured Policy, and the policy tries to resolve the second singleton: `services2.GetService<IEIAuthentication>()`.  (And the execution has moved to a different thread: I forgot to note during step-debugging whether this happened at the point of an async Task invocation during the httpClient call, or if the DI resolver [forked the singleton resolution to a new thread](https://github.com/dotnet/extensions/blob/32cc8162ff38356b293611138d361f757a62e025/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs#L76-L79); but the debug view in Visual Studio confirms the two threads.)
4. Trying to resolve the second singleton tries to take out the lock-for-resolving-singletons, but that lock is held by another thread because we are still executing the constructor of `MainApp` - deadlock!

---

I tested, and using the Async Initialization pattern (see previous comment) solves this. In that variant, the constructor of `MainApp` stores the `Task` returned for the async call, and this is returned before the async call reaches trying to resolve the second singleton; hence no deadlock.

As the deadlock only occurs when the DI has to create the instances of both singletons for you, you can also remove the deadlock by creating at least one of the two singletons yourself at DI registration-time, eg:

    services.AddSingleton<MainApp>();
    services.AddSingleton<IEIAuthentication>(new EIAuthenticationService());

However, not blocking on async work in the constructor of `MainApp` would be preferable.

**Comment by reisenberger** [comment] 2020-02-03 07:41
Closing, as a diagnosis and several resolutions have been provided, and there is nothing we can change in the Polly codebase around this.  If you have further questions though, just post and we can re-open.

You could also raise this with the [dotnet/extensions](https://github.com/dotnet/extensions/) team, who own both the HttpClientFactory and DI code, but I wouldn't be surprised if the response was that heavy-lifting (such as making and blocking on async calls) during a constructor is not recommended or supported.

**Closed by reisenberger** 2020-02-03 07:41 UTC
Labels: issue is outside Polly
