### ISSUE TITLE
Problems with Polly 5.x importing into Xamarin Forms PCL project

### ISSUE THREAD

**Issue by ZoranBebic** [App-vNext/Polly#237] opened 2017-03-22 11:30 UTC
Hey 

We are using Polly 4.3.0 still but wanted to upgrade however I have this issue on a project (PCL Xamarin.Forms) that is targeting "portable46-net451+win81", version 5.x tries to import as if the project is .NetStandard based and fails. Any clue as to what might be the issue?

I am also looking forward to the upcoming cache implementation (would like to replace current Akavache), any idea how far along that particular feature might be?

**Comment by ericbrunner** [comment] 2017-03-22 15:58
@ZoranBebic Hi Zoran, I guess my issue is related: https://github.com/App-vNext/Polly/issues/238
I am not so experienced with Polly . Does v 4.3.0 the job as well ? So would it be sufficient to use that version? In case of yes, I could go that way otherwise I get rid of Polly.

**Comment by ZoranBebic** [comment] 2017-03-23 11:40
@ericbrunner Hey Eric!
Older version still packs a punch and is extremely worth using. It lacks new features version 5.x brought in but maybe you don't need them so definitely give it a try (I only use Retry for now and love it). One thing for me particularly in version 5 is Timeout and an upcoming Cache implementation that I'd love to try.

Due to a bug in Xamarin.Forms sadly I am unable to target NetStandard just yet.

**Comment by ericbrunner** [comment] 2017-03-23 17:44
@ZoranBebic Thank you Zoran for your support. I use Polly in Windows Services so I really like it and wanted to use it in Xamarin.Forms , too. Ok. I try the v.4.3.0 you mentioned above.

**Comment by reisenberger** [comment] 2017-03-25 10:55
@ericbrunner @ZoranBebic  Yes, Polly v5+ does not contain a PCL target any more, and as such may not install in a Xamarin Forms PCL project.  At [Polly v5.0.2](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md#502-alpha), following the Microsoft recommendation, Polly moved to targeting multiple platforms via .Net Standard rather than PCL.  

To reference Polly v5+ from Xamarin, you may need to [update your Xamarin forms projects to target .NET Standard](https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/) (also [notes for Visual Studio 2017](https://xamarinhelp.com/visual-studio-2017-net-standard-xamarin/)).  This is not a process I have been through, so further feedback here welcome.

@julien-mialon helped resolve some Xamarin PCL issues in #228 and may also be able to help?

Polly v4.3.0 can be referenced from PCL-based projects.  Differences between Polly v4.3.0 and latest are documented extensively [in the changelog](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md) and [milestone-tagging of issues and PRs](https://github.com/App-vNext/Polly/milestones?state=closed).

**Comment by Julien-Mialon** [comment] 2017-03-26 19:04
@ericbrunner  @ZoranBebic @reisenberger Just tried to install Polly in a PCL project targeting net451, win81, Xamarin *. It worked perfectly, but you need to have one of the last version of nuget to make it works correctly. You don't need to target netstandard to use netstandard project, it has retrocompatibility with pcl profile.

**Comment by reisenberger** [comment] 2017-03-26 20:19
@Julien-Mialon Perfect! Thanks for the update.  @ericbrunner @ZoranBebic Does this help?

**Comment by ZoranBebic** [comment] 2017-03-27 06:57
That's great news however I'm not sure I understand this statement "It worked perfectly, but you need to have one of the last version of nuget to make it works correctly."

Are you referring to Nuget version 4+ that comes already as part of latest VisualStudio? I haven't tried updating to Polly 5.x since I switched to VS2017 and having deadline looming just around the corner I won't be able to try this for another week. Will definitely post with the results soon. Thanks!

**Comment by Julien-Mialon** [comment] 2017-03-27 07:03
Just updated to last 3.X nuget version works perfectly, I tried with VS2015 and Xamarin Studio.

**Comment by ericbrunner** [comment] 2017-03-28 09:40
@Julien-Mialon Thank you very much. I don't think that is the full truth. As Adam Pedley blogged, you can't reference a .NET Standard library from a PCL project:https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/

But you make me curious. I will try, because if you are right I could reference any .NET Standard library in my PCL with profile 259, not only my beloved Polly.

Further I have to check if my hosted agent in VSTS , which I use to build Xamarin.Forms Apps, already supports the 3.x nuget.exe.

It would definitly help when you can put a sample project either on gist.github.com or a public repo.

**Comment by Julien-Mialon** [comment] 2017-03-28 09:57
@ericbrunner That's right, you can not reference netstandard to PCL with project reference but with nuget, it works. I will setup a sample project this evening.

You can check that link for PCL profile & netstandard equivalent https://docs.microsoft.com/en-us/dotnet/articles/standard/library, in Profile 259 you should be able to add any nuget targeting netstandard1.0.

**Comment by Julien-Mialon** [comment] 2017-03-28 11:09
@ericbrunner I did the sample, it's available there : https://github.com/Julien-Mialon/PollyNetstandardSample
You can check in the csproj file that Polly is referenced by using netstandard1.0 version 
```xml
<Reference Include="Polly, Version=5.0.6.0, Culture=neutral, processorArchitecture=MSIL">
  <HintPath>..\packages\Polly.5.0.6\lib\netstandard1.0\Polly.dll</HintPath>
  <Private>True</Private>
</Reference>
```
My nuget version is 3.5.0.1938
Only thing that I can think of, it's I have the .Net Core SDK installed (which add some support for netstandard project).

Hope this could help.

**Comment by ericbrunner** [comment] 2017-03-28 14:19
@Julien-Mialon Awesome! Thanks for your support.

**Comment by reisenberger** [comment] 2017-05-04 19:11
Closing due to no further activity (re-open if further assistance needed)

@Julien-Mialon Je vous remercie encore!

@ZoranBebic For updates on the cache policy, follow #136

**Closed by reisenberger** 2017-05-04 19:11 UTC
Labels: target frameworks

**Comment by mikegottlieb** [comment] 2017-05-10 20:41
I just installed VS for Mac now that it is out of preview. I had to set my Mono version to 4.8 because I'm still on a slightly older version of Xamarin.Forms. When I try to build I get the following error.

> The primary reference "Polly" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".

I'm was originally using v5.0.5 of Polly, but I also tried v5.0.6. I also updated my nuget just in case that was the problem, but unfortunately non of that helped.

What is really strange is that I can build fine in Xamarin Studio. Any ideas?

**Comment by reisenberger** [comment] 2017-05-10 21:41
@mikegottlieb Hmm, I'm not a Xamarin dev.  Does @Julien-Mialon 's sample from [here](https://github.com/App-vNext/Polly/issues/237#issuecomment-289736847) help?  (maybe you have been through these suggestions already, but in case ...).  

Other possible issue with clues [here](https://github.com/Humanizr/Humanizer/issues/573), [here](https://github.com/dotnet/roslyn/issues/11067), [here](https://github.com/paulcbetts/splat/issues/149) and [here](https://github.com/onovotny/Zeroconf/issues/60).  

Also, does [Oren Novotny's sample app here](https://github.com/onovotny/SampleXamFormsWithNetStandard) help? Or his related [updated discussion](https://oren.codes/2017/04/23/using-xamarin-forms-with-net-standard-vs-2017-edition/)?

Community / @Julien-Mialon ? - any ideas?

**Comment by mikegottlieb** [comment] 2017-05-10 21:58
I manually edited the project file to reference the net45 version of Polly rather than the netstandard1.0 version and now my project builds although I get some strange warnings.

It looks like I'm not the only one seeing weirdness here. One of your links linked to a newer open issue in Humanizer [here](https://github.com/Humanizr/Humanizer/issues/621)

I guess maybe this is just a VS for Mac regression and I need to wait for an update. I'm not quite ready to retarget my whole application, but thanks for the link from Oren. I'm sure that will help when I'm ready.

**Comment by reisenberger** [comment] 2017-05-10 22:14
No problem.  If there is something we can do to improve the configuration of Polly's .NETStandard csproj, also v open to do that.  We will (soon-ish) move Polly on to VS2017, take advantage of the new tooling and poss. opportunity to straighten out as many of the old-tooling kinks as possible ... feels like .NETStandard tooling is (eventually) settling.

**Comment by Julien-Mialon** [comment] 2017-05-11 07:27
Hello @mikegottlieb 

Got this error for some packages recently on Xamarin Studio & Vs For Mac (alpha, currently downloading the stable version released yesterday). A workaround that I used was building from CLI by manually launching xbuild, after that XS & VSfM managed to use Polly. But it's definitely a bug in XS & VSfM since CLI works just fine.

I will check if the issue is still present for me with last version of VSfM.

If it still there, the only reason I can think of is last version of Polly still use project.json system, maybe updating to VS2017 format with csproj could work, I don't know if it's something planned @reisenberger ?

**Comment by Julien-Mialon** [comment] 2017-05-16 14:13
Didn't have this problem anymore with last stable version of Visual Studio for Mac.
I'm running it with Mono 5.0

**Comment by mikegottlieb** [comment] 2017-05-30 15:48
I'm running Mono 4.8 because I cannot yet update to 5.0 due to other constraints.
